// Copyright Epic Games, Inc. All Rights Reserved.

#include "CPBEditorAutomationBFL.h"

#include "CPBLevelPlacementDTO.h"
#include "CPBMasterSheetDTO.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "Core/CPBTypes.h"
#include "DataTableEditorUtils.h"
#include "Editor.h"
#include "Engine/DataTable.h"
#include "Engine/Engine.h"
#include "Engine/World.h"
#include "EngineUtils.h"
#include "GameFramework/Actor.h"
#include "Interaction/CPBInteractorBase.h"
#include "Misc/FileHelper.h"
#include "Misc/PackageName.h"
#include "Misc/Paths.h"
#include "ScopedTransaction.h"
#include "Sequence/CPBSequence.h"
#include "Sequence/CPBSequenceManager.h"
#include "Serialization/Csv/CsvParser.h"
#include "Sound/SoundBase.h"
#include "UObject/Package.h"
#include "UObject/SoftObjectPath.h"
#include "UObject/UnrealType.h"
#include "XmlFile.h"
#include "XmlNode.h"

THIRD_PARTY_INCLUDES_START
#include "zlib.h"
THIRD_PARTY_INCLUDES_END

DEFINE_LOG_CATEGORY_STATIC(LogCPBEditorAutomation, Log, All);

namespace
{
const FName CPBAutoGeneratedActorTag(TEXT("CPB_AutoGenerated"));
const FName CPBAutomationSystemTag(TEXT("CPB_Automation"));

enum class ECPBEditorAutomationMessageType : uint8
{
	Info,
	Warning,
	Error
};

void CPBReportAutomationMessage(const FString& Message, ECPBEditorAutomationMessageType MessageType)
{
	switch (MessageType)
	{
	case ECPBEditorAutomationMessageType::Info:
		UE_LOG(LogCPBEditorAutomation, Log, TEXT("%s"), *Message);
		break;
	case ECPBEditorAutomationMessageType::Warning:
		UE_LOG(LogCPBEditorAutomation, Warning, TEXT("%s"), *Message);
		break;
	case ECPBEditorAutomationMessageType::Error:
		UE_LOG(LogCPBEditorAutomation, Error, TEXT("%s"), *Message);
		break;
	default:
		UE_LOG(LogCPBEditorAutomation, Log, TEXT("%s"), *Message);
		break;
	}

	if (GEngine)
	{
		const FColor MessageColor = MessageType == ECPBEditorAutomationMessageType::Error
			? FColor::Red
			: MessageType == ECPBEditorAutomationMessageType::Warning
				? FColor::Yellow
				: FColor::Green;

		GEngine->AddOnScreenDebugMessage(-1, 6.0f, MessageColor, Message);
	}
}

struct FCPBCsvRecord
{
	FName RowName = NAME_None;
	TMap<FString, FString> Cells;
};

struct FCPBGeneratedDataTables
{
	TObjectPtr<UDataTable> LevelPlacementTable = nullptr;
	TObjectPtr<UDataTable> ScenarioFlowTable = nullptr;
	TObjectPtr<UDataTable> ActionEventTable = nullptr;
	TObjectPtr<UDataTable> DictionaryTable = nullptr;
	TObjectPtr<UDataTable> ScenarioTable = nullptr;
	TObjectPtr<UDataTable> StringTable = nullptr;
	TObjectPtr<UDataTable> SoundTable = nullptr;
	TObjectPtr<UDataTable> NarrationTable = nullptr;
};

struct FCPBZipEntryInfo
{
	FString Name;
	uint16 CompressionMethod = 0;
	uint32 CompressedSize = 0;
	uint32 UncompressedSize = 0;
	uint32 LocalHeaderOffset = 0;
};

struct FCPBXlsxSheetInfo
{
	FString Name;
	FString RelationshipId;
	FString Path;
};

uint16 CPBReadUInt16(const TArray<uint8>& Data, int64 Offset)
{
	if (!Data.IsValidIndex(Offset + 1))
	{
		return 0;
	}

	return static_cast<uint16>(Data[Offset]) |
		(static_cast<uint16>(Data[Offset + 1]) << 8);
}

uint32 CPBReadUInt32(const TArray<uint8>& Data, int64 Offset)
{
	if (!Data.IsValidIndex(Offset + 3))
	{
		return 0;
	}

	return static_cast<uint32>(Data[Offset]) |
		(static_cast<uint32>(Data[Offset + 1]) << 8) |
		(static_cast<uint32>(Data[Offset + 2]) << 16) |
		(static_cast<uint32>(Data[Offset + 3]) << 24);
}

FString CPBBytesToUtf8String(const TArray<uint8>& Bytes)
{
	if (Bytes.Num() == 0)
	{
		return FString();
	}

	FUTF8ToTCHAR Converter(reinterpret_cast<const ANSICHAR*>(Bytes.GetData()), Bytes.Num());
	return FString(Converter.Length(), Converter.Get());
}

bool CPBInflateRawDeflate(const uint8* CompressedData, int32 CompressedSize, TArray<uint8>& OutUncompressed, int32 UncompressedSize)
{
	OutUncompressed.SetNumUninitialized(UncompressedSize);
	if (UncompressedSize == 0)
	{
		return true;
	}

	z_stream Stream;
	FMemory::Memzero(Stream);
	Stream.next_in = const_cast<Bytef*>(reinterpret_cast<const Bytef*>(CompressedData));
	Stream.avail_in = static_cast<uInt>(CompressedSize);
	Stream.next_out = reinterpret_cast<Bytef*>(OutUncompressed.GetData());
	Stream.avail_out = static_cast<uInt>(UncompressedSize);

	const int32 InitResult = inflateInit2(&Stream, -MAX_WBITS);
	if (InitResult != Z_OK)
	{
		return false;
	}

	const int32 InflateResult = inflate(&Stream, Z_FINISH);
	inflateEnd(&Stream);
	return InflateResult == Z_STREAM_END && Stream.total_out == static_cast<uLong>(UncompressedSize);
}

bool CPBReadZipDirectory(const TArray<uint8>& ZipBytes, TMap<FString, FCPBZipEntryInfo>& OutEntries)
{
	OutEntries.Reset();

	const uint32 EndOfCentralDirectorySignature = 0x06054b50;
	const uint32 CentralDirectoryHeaderSignature = 0x02014b50;
	const int64 MaxSearchBytes = FMath::Min<int64>(ZipBytes.Num(), 65557);

	int64 EndOfCentralDirectoryOffset = INDEX_NONE;
	for (int64 Offset = ZipBytes.Num() - 22; Offset >= ZipBytes.Num() - MaxSearchBytes && Offset >= 0; --Offset)
	{
		if (CPBReadUInt32(ZipBytes, Offset) == EndOfCentralDirectorySignature)
		{
			EndOfCentralDirectoryOffset = Offset;
			break;
		}
	}

	if (EndOfCentralDirectoryOffset == INDEX_NONE)
	{
		return false;
	}

	const uint16 EntryCount = CPBReadUInt16(ZipBytes, EndOfCentralDirectoryOffset + 10);
	const uint32 CentralDirectoryOffset = CPBReadUInt32(ZipBytes, EndOfCentralDirectoryOffset + 16);

	int64 Offset = CentralDirectoryOffset;
	for (uint16 EntryIndex = 0; EntryIndex < EntryCount; ++EntryIndex)
	{
		if (CPBReadUInt32(ZipBytes, Offset) != CentralDirectoryHeaderSignature)
		{
			return false;
		}

		FCPBZipEntryInfo EntryInfo;
		EntryInfo.CompressionMethod = CPBReadUInt16(ZipBytes, Offset + 10);
		EntryInfo.CompressedSize = CPBReadUInt32(ZipBytes, Offset + 20);
		EntryInfo.UncompressedSize = CPBReadUInt32(ZipBytes, Offset + 24);
		const uint16 FileNameLength = CPBReadUInt16(ZipBytes, Offset + 28);
		const uint16 ExtraFieldLength = CPBReadUInt16(ZipBytes, Offset + 30);
		const uint16 CommentLength = CPBReadUInt16(ZipBytes, Offset + 32);
		EntryInfo.LocalHeaderOffset = CPBReadUInt32(ZipBytes, Offset + 42);

		if (!ZipBytes.IsValidIndex(Offset + 46 + FileNameLength - 1))
		{
			return false;
		}

		const TArrayView<const uint8> NameBytes(ZipBytes.GetData() + Offset + 46, FileNameLength);
		EntryInfo.Name = FString(FUTF8ToTCHAR(reinterpret_cast<const ANSICHAR*>(NameBytes.GetData()), NameBytes.Num()).Get());
		EntryInfo.Name.ReplaceInline(TEXT("\\"), TEXT("/"));

		OutEntries.Add(EntryInfo.Name, EntryInfo);
		Offset += 46 + FileNameLength + ExtraFieldLength + CommentLength;
	}

	return true;
}

bool CPBExtractZipEntry(const TArray<uint8>& ZipBytes, const FCPBZipEntryInfo& EntryInfo, TArray<uint8>& OutBytes)
{
	const uint32 LocalHeaderSignature = 0x04034b50;
	const int64 LocalOffset = EntryInfo.LocalHeaderOffset;
	if (CPBReadUInt32(ZipBytes, LocalOffset) != LocalHeaderSignature)
	{
		return false;
	}

	const uint16 FileNameLength = CPBReadUInt16(ZipBytes, LocalOffset + 26);
	const uint16 ExtraFieldLength = CPBReadUInt16(ZipBytes, LocalOffset + 28);
	const int64 DataOffset = LocalOffset + 30 + FileNameLength + ExtraFieldLength;
	if (!ZipBytes.IsValidIndex(DataOffset + EntryInfo.CompressedSize - 1))
	{
		return false;
	}

	const uint8* CompressedData = ZipBytes.GetData() + DataOffset;
	if (EntryInfo.CompressionMethod == 0)
	{
		OutBytes.SetNumUninitialized(EntryInfo.UncompressedSize);
		FMemory::Memcpy(OutBytes.GetData(), CompressedData, EntryInfo.UncompressedSize);
		return true;
	}

	if (EntryInfo.CompressionMethod == 8)
	{
		return CPBInflateRawDeflate(CompressedData, EntryInfo.CompressedSize, OutBytes, EntryInfo.UncompressedSize);
	}

	return false;
}

bool CPBReadXlsxTextEntry(
	const TArray<uint8>& XlsxBytes,
	const TMap<FString, FCPBZipEntryInfo>& ZipEntries,
	const FString& EntryPath,
	FString& OutText)
{
	const FCPBZipEntryInfo* EntryInfo = ZipEntries.Find(EntryPath);
	if (!EntryInfo)
	{
		return false;
	}

	TArray<uint8> EntryBytes;
	if (!CPBExtractZipEntry(XlsxBytes, *EntryInfo, EntryBytes))
	{
		return false;
	}

	OutText = CPBBytesToUtf8String(EntryBytes);
	return true;
}

const FXmlNode* CPBFindXmlChildByTag(const FXmlNode* Node, const FString& Tag)
{
	if (!Node)
	{
		return nullptr;
	}

	for (const FXmlNode* Child : Node->GetChildrenNodes())
	{
		if (Child && Child->GetTag().Equals(Tag, ESearchCase::IgnoreCase))
		{
			return Child;
		}
	}

	return nullptr;
}

void CPBCollectXmlTextNodes(const FXmlNode* Node, FString& InOutText)
{
	if (!Node)
	{
		return;
	}

	if (Node->GetTag().Equals(TEXT("t"), ESearchCase::IgnoreCase))
	{
		InOutText += Node->GetContent();
	}

	for (const FXmlNode* Child : Node->GetChildrenNodes())
	{
		CPBCollectXmlTextNodes(Child, InOutText);
	}
}

bool CPBParseSharedStringsXml(const FString& SharedStringsXml, TArray<FString>& OutSharedStrings)
{
	OutSharedStrings.Reset();

	if (SharedStringsXml.IsEmpty())
	{
		return true;
	}

	FXmlFile XmlFile(SharedStringsXml, EConstructMethod::ConstructFromBuffer);
	if (!XmlFile.IsValid() || !XmlFile.GetRootNode())
	{
		return false;
	}

	for (const FXmlNode* SharedStringNode : XmlFile.GetRootNode()->GetChildrenNodes())
	{
		if (!SharedStringNode || !SharedStringNode->GetTag().Equals(TEXT("si"), ESearchCase::IgnoreCase))
		{
			continue;
		}

		FString Text;
		CPBCollectXmlTextNodes(SharedStringNode, Text);
		OutSharedStrings.Add(Text);
	}

	return true;
}

int32 CPBColumnIndexFromCellReference(const FString& CellReference)
{
	int32 ColumnIndex = 0;
	for (int32 CharIndex = 0; CharIndex < CellReference.Len(); ++CharIndex)
	{
		const TCHAR Character = CellReference[CharIndex];
		if (!FChar::IsAlpha(Character))
		{
			break;
		}

		ColumnIndex = ColumnIndex * 26 + (FChar::ToUpper(Character) - TEXT('A') + 1);
	}

	return ColumnIndex > 0 ? ColumnIndex - 1 : INDEX_NONE;
}

FString CPBGetXlsxCellText(const FXmlNode* CellNode, const TArray<FString>& SharedStrings)
{
	if (!CellNode)
	{
		return FString();
	}

	const FString CellType = CellNode->GetAttribute(TEXT("t"));
	if (CellType.Equals(TEXT("inlineStr"), ESearchCase::IgnoreCase))
	{
		if (const FXmlNode* InlineStringNode = CPBFindXmlChildByTag(CellNode, TEXT("is")))
		{
			FString InlineText;
			CPBCollectXmlTextNodes(InlineStringNode, InlineText);
			return InlineText;
		}

		return FString();
	}

	const FXmlNode* ValueNode = CPBFindXmlChildByTag(CellNode, TEXT("v"));
	const FString RawValue = ValueNode ? ValueNode->GetContent() : FString();

	if (CellType.Equals(TEXT("s"), ESearchCase::IgnoreCase))
	{
		const int32 SharedStringIndex = FCString::Atoi(*RawValue);
		return SharedStrings.IsValidIndex(SharedStringIndex) ? SharedStrings[SharedStringIndex] : FString();
	}

	if (CellType.Equals(TEXT("b"), ESearchCase::IgnoreCase))
	{
		return RawValue == TEXT("1") ? TEXT("TRUE") : TEXT("FALSE");
	}

	return RawValue;
}

bool CPBParseWorksheetXml(const FString& SheetXml, const TArray<FString>& SharedStrings, TArray<TArray<FString>>& OutRows)
{
	OutRows.Reset();

	FXmlFile XmlFile(SheetXml, EConstructMethod::ConstructFromBuffer);
	if (!XmlFile.IsValid() || !XmlFile.GetRootNode())
	{
		return false;
	}

	const FXmlNode* SheetDataNode = CPBFindXmlChildByTag(XmlFile.GetRootNode(), TEXT("sheetData"));
	if (!SheetDataNode)
	{
		return false;
	}

	for (const FXmlNode* RowNode : SheetDataNode->GetChildrenNodes())
	{
		if (!RowNode || !RowNode->GetTag().Equals(TEXT("row"), ESearchCase::IgnoreCase))
		{
			continue;
		}

		TArray<FString> RowValues;
		int32 NextColumnIndex = 0;

		for (const FXmlNode* CellNode : RowNode->GetChildrenNodes())
		{
			if (!CellNode || !CellNode->GetTag().Equals(TEXT("c"), ESearchCase::IgnoreCase))
			{
				continue;
			}

			int32 ColumnIndex = CPBColumnIndexFromCellReference(CellNode->GetAttribute(TEXT("r")));
			if (ColumnIndex == INDEX_NONE)
			{
				ColumnIndex = NextColumnIndex;
			}

			while (RowValues.Num() <= ColumnIndex)
			{
				RowValues.Add(FString());
			}

			RowValues[ColumnIndex] = CPBGetXlsxCellText(CellNode, SharedStrings);
			NextColumnIndex = ColumnIndex + 1;
		}

		OutRows.Add(RowValues);
	}

	return true;
}

bool CPBParseWorkbookSheets(
	const FString& WorkbookXml,
	const FString& WorkbookRelationshipsXml,
	TArray<FCPBXlsxSheetInfo>& OutSheets)
{
	OutSheets.Reset();

	FXmlFile WorkbookFile(WorkbookXml, EConstructMethod::ConstructFromBuffer);
	FXmlFile RelationshipsFile(WorkbookRelationshipsXml, EConstructMethod::ConstructFromBuffer);
	if (!WorkbookFile.IsValid() || !RelationshipsFile.IsValid() || !WorkbookFile.GetRootNode() || !RelationshipsFile.GetRootNode())
	{
		return false;
	}

	TMap<FString, FString> RelationshipTargets;
	for (const FXmlNode* RelationshipNode : RelationshipsFile.GetRootNode()->GetChildrenNodes())
	{
		if (!RelationshipNode || !RelationshipNode->GetTag().Equals(TEXT("Relationship"), ESearchCase::IgnoreCase))
		{
			continue;
		}

		FString Target = RelationshipNode->GetAttribute(TEXT("Target"));
		Target.ReplaceInline(TEXT("\\"), TEXT("/"));
		if (Target.StartsWith(TEXT("/")))
		{
			Target.RightChopInline(1);
		}
		else
		{
			Target = TEXT("xl/") + Target;
		}

		RelationshipTargets.Add(RelationshipNode->GetAttribute(TEXT("Id")), Target);
	}

	const FXmlNode* SheetsNode = CPBFindXmlChildByTag(WorkbookFile.GetRootNode(), TEXT("sheets"));
	if (!SheetsNode)
	{
		return false;
	}

	for (const FXmlNode* SheetNode : SheetsNode->GetChildrenNodes())
	{
		if (!SheetNode || !SheetNode->GetTag().Equals(TEXT("sheet"), ESearchCase::IgnoreCase))
		{
			continue;
		}

		FCPBXlsxSheetInfo SheetInfo;
		SheetInfo.Name = SheetNode->GetAttribute(TEXT("name"));
		SheetInfo.RelationshipId = SheetNode->GetAttribute(TEXT("r:id"));
		if (const FString* TargetPath = RelationshipTargets.Find(SheetInfo.RelationshipId))
		{
			SheetInfo.Path = *TargetPath;
			OutSheets.Add(SheetInfo);
		}
	}

	return OutSheets.Num() > 0;
}

bool CPBLoadXlsxSheets(const FString& ExcelFilePath, TMap<FString, TArray<TArray<FString>>>& OutSheets)
{
	OutSheets.Reset();

	TArray<uint8> XlsxBytes;
	if (!FFileHelper::LoadFileToArray(XlsxBytes, *ExcelFilePath))
	{
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB Excel automation failed: cannot read '%s'."), *ExcelFilePath),
			ECPBEditorAutomationMessageType::Error);
		return false;
	}

	TMap<FString, FCPBZipEntryInfo> ZipEntries;
	if (!CPBReadZipDirectory(XlsxBytes, ZipEntries))
	{
		CPBReportAutomationMessage(TEXT("CPB Excel automation failed: invalid .xlsx ZIP directory."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	FString WorkbookXml;
	FString RelationshipsXml;
	if (!CPBReadXlsxTextEntry(XlsxBytes, ZipEntries, TEXT("xl/workbook.xml"), WorkbookXml) ||
		!CPBReadXlsxTextEntry(XlsxBytes, ZipEntries, TEXT("xl/_rels/workbook.xml.rels"), RelationshipsXml))
	{
		CPBReportAutomationMessage(TEXT("CPB Excel automation failed: workbook metadata is missing."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	TArray<FString> SharedStrings;
	FString SharedStringsXml;
	if (CPBReadXlsxTextEntry(XlsxBytes, ZipEntries, TEXT("xl/sharedStrings.xml"), SharedStringsXml))
	{
		if (!CPBParseSharedStringsXml(SharedStringsXml, SharedStrings))
		{
			CPBReportAutomationMessage(TEXT("CPB Excel automation failed: shared strings could not be parsed."), ECPBEditorAutomationMessageType::Error);
			return false;
		}
	}

	TArray<FCPBXlsxSheetInfo> SheetInfos;
	if (!CPBParseWorkbookSheets(WorkbookXml, RelationshipsXml, SheetInfos))
	{
		CPBReportAutomationMessage(TEXT("CPB Excel automation failed: workbook sheet list could not be parsed."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	for (const FCPBXlsxSheetInfo& SheetInfo : SheetInfos)
	{
		FString SheetXml;
		if (!CPBReadXlsxTextEntry(XlsxBytes, ZipEntries, SheetInfo.Path, SheetXml))
		{
			CPBReportAutomationMessage(
				FString::Printf(TEXT("CPB Excel automation warning: sheet '%s' XML was not found."), *SheetInfo.Name),
				ECPBEditorAutomationMessageType::Warning);
			continue;
		}

		TArray<TArray<FString>> SheetRows;
		if (CPBParseWorksheetXml(SheetXml, SharedStrings, SheetRows))
		{
			OutSheets.Add(SheetInfo.Name, MoveTemp(SheetRows));
		}
	}

	return OutSheets.Num() > 0;
}

FString CPBMakeCsvCell(const FString& InValue)
{
	FString Value = InValue;
	Value.ReplaceInline(TEXT("\""), TEXT("\"\""));

	if (Value.Contains(TEXT(",")) || Value.Contains(TEXT("\"")) || Value.Contains(TEXT("\n")) || Value.Contains(TEXT("\r")))
	{
		return FString::Printf(TEXT("\"%s\""), *Value);
	}

	return Value;
}

bool CPBWriteRowsToCsv(const TArray<TArray<FString>>& Rows, const FString& CsvFilePath)
{
	TArray<FString> Lines;
	Lines.Reserve(Rows.Num());

	for (const TArray<FString>& Row : Rows)
	{
		TArray<FString> Cells;
		Cells.Reserve(Row.Num());
		for (const FString& Cell : Row)
		{
			Cells.Add(CPBMakeCsvCell(Cell));
		}

		Lines.Add(FString::Join(Cells, TEXT(",")));
	}

	return FFileHelper::SaveStringToFile(
		FString::Join(Lines, TEXT("\n")),
		*CsvFilePath,
		FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM);
}

bool CPBConvertXlsxToMasterCsvFolder(const FString& ExcelFilePath, FString& OutCsvFolderPath)
{
	const FString FullExcelFilePath = FPaths::ConvertRelativePathToFull(ExcelFilePath);
	if (!FPaths::FileExists(FullExcelFilePath))
	{
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB Excel automation failed: Excel file does not exist at '%s'."), *FullExcelFilePath),
			ECPBEditorAutomationMessageType::Error);
		return false;
	}

	TMap<FString, TArray<TArray<FString>>> Sheets;
	if (!CPBLoadXlsxSheets(FullExcelFilePath, Sheets))
	{
		return false;
	}

	const FString WorkbookBaseName = FPaths::GetBaseFilename(FullExcelFilePath);
	OutCsvFolderPath = FPaths::Combine(FPaths::ProjectSavedDir(), TEXT("CPBMasterExcelCache"), WorkbookBaseName);
	IFileManager::Get().MakeDirectory(*OutCsvFolderPath, true);

	static const TArray<FString> RequiredSheetNames =
	{
		TEXT("Set_Level"),
		TEXT("DT_ScenarioFlow"),
		TEXT("DT_ActionEvent"),
		TEXT("DT_Dictionary")
	};

	bool bWroteRequiredSheets = true;
	for (const FString& SheetName : RequiredSheetNames)
	{
		const TArray<TArray<FString>>* Rows = Sheets.Find(SheetName);
		if (!Rows)
		{
			bWroteRequiredSheets = false;
			CPBReportAutomationMessage(
				FString::Printf(TEXT("CPB Excel automation warning: required sheet '%s' was not found in '%s'."), *SheetName, *FullExcelFilePath),
				ECPBEditorAutomationMessageType::Warning);
			continue;
		}

		const FString CsvFilePath = FPaths::Combine(OutCsvFolderPath, SheetName + TEXT(".csv"));
		if (!CPBWriteRowsToCsv(*Rows, CsvFilePath))
		{
			bWroteRequiredSheets = false;
			CPBReportAutomationMessage(
				FString::Printf(TEXT("CPB Excel automation failed: could not write temporary CSV '%s'."), *CsvFilePath),
				ECPBEditorAutomationMessageType::Error);
		}
	}

	return bWroteRequiredSheets;
}

FString CPBGetDefaultMasterExcelFolder()
{
	return FPaths::Combine(FPaths::ProjectSavedDir(), TEXT("CPBMasterExcel"));
}

bool CPBFindLatestExcelFileInFolder(const FString& InExcelFolderPath, FString& OutExcelFilePath)
{
	FString ExcelFolderPath = InExcelFolderPath;
	if (ExcelFolderPath.IsEmpty())
	{
		ExcelFolderPath = CPBGetDefaultMasterExcelFolder();
	}

	const FString FullExcelFolderPath = FPaths::ConvertRelativePathToFull(ExcelFolderPath);
	if (!FPaths::DirectoryExists(FullExcelFolderPath))
	{
		IFileManager::Get().MakeDirectory(*FullExcelFolderPath, true);
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB Excel automation folder was created. Place an .xlsx file here and run again: '%s'."), *FullExcelFolderPath),
			ECPBEditorAutomationMessageType::Warning);
		return false;
	}

	TArray<FString> ExcelFiles;
	IFileManager::Get().FindFiles(ExcelFiles, *FPaths::Combine(FullExcelFolderPath, TEXT("*.xlsx")), true, false);

	FDateTime LatestTimestamp = FDateTime::MinValue();
	for (const FString& ExcelFile : ExcelFiles)
	{
		if (ExcelFile.StartsWith(TEXT("~$")))
		{
			continue;
		}

		const FString CandidatePath = FPaths::Combine(FullExcelFolderPath, ExcelFile);
		const FDateTime CandidateTimestamp = IFileManager::Get().GetTimeStamp(*CandidatePath);
		if (OutExcelFilePath.IsEmpty() || CandidateTimestamp > LatestTimestamp)
		{
			LatestTimestamp = CandidateTimestamp;
			OutExcelFilePath = CandidatePath;
		}
	}

	if (OutExcelFilePath.IsEmpty())
	{
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB Excel automation failed: no .xlsx file found in '%s'."), *FullExcelFolderPath),
			ECPBEditorAutomationMessageType::Warning);
		return false;
	}

	return true;
}

FString CPBCleanCell(const FString& InValue)
{
	FString Value = InValue;
	Value.TrimStartAndEndInline();

	if (Value.Equals(TEXT("None"), ESearchCase::IgnoreCase) ||
		Value.Equals(TEXT("N/A"), ESearchCase::IgnoreCase) ||
		Value.Equals(TEXT("NA"), ESearchCase::IgnoreCase) ||
		Value.Equals(TEXT("-"), ESearchCase::IgnoreCase))
	{
		return FString();
	}

	return Value;
}

FString CPBNormalizeHeader(const FString& InHeader)
{
	FString Header = InHeader;
	Header.TrimStartAndEndInline();

	int32 ParenthesisIndex = INDEX_NONE;
	if (Header.FindChar(TEXT('('), ParenthesisIndex))
	{
		Header = Header.Left(ParenthesisIndex);
		Header.TrimStartAndEndInline();
	}

	Header.ReplaceInline(TEXT(" "), TEXT(""));
	Header.ReplaceInline(TEXT("\t"), TEXT(""));
	return Header;
}

FName CPBNameFromCell(const FString& InValue)
{
	const FString CleanValue = CPBCleanCell(InValue);
	return CleanValue.IsEmpty() ? NAME_None : FName(*CleanValue);
}

FString CPBGetCell(const FCPBCsvRecord& Record, const FString& Key)
{
	if (const FString* Value = Record.Cells.Find(Key))
	{
		return CPBCleanCell(*Value);
	}

	return FString();
}

bool CPBTryParseVectorCell(const FString& InValue, FVector& OutVector)
{
	const FString CleanValue = CPBCleanCell(InValue);
	if (CleanValue.IsEmpty())
	{
		return false;
	}

	TArray<FString> Parts;
	CleanValue.ParseIntoArray(Parts, TEXT(","), true);
	if (Parts.Num() != 3)
	{
		return OutVector.InitFromString(CleanValue);
	}

	OutVector.X = FCString::Atof(*Parts[0].TrimStartAndEnd());
	OutVector.Y = FCString::Atof(*Parts[1].TrimStartAndEnd());
	OutVector.Z = FCString::Atof(*Parts[2].TrimStartAndEnd());
	return true;
}

bool CPBTryParseRotatorCell(const FString& InValue, FRotator& OutRotator)
{
	const FString CleanValue = CPBCleanCell(InValue);
	if (CleanValue.IsEmpty())
	{
		return false;
	}

	TArray<FString> Parts;
	CleanValue.ParseIntoArray(Parts, TEXT(","), true);
	if (Parts.Num() != 3)
	{
		return OutRotator.InitFromString(CleanValue);
	}

	OutRotator.Pitch = FCString::Atof(*Parts[0].TrimStartAndEnd());
	OutRotator.Yaw = FCString::Atof(*Parts[1].TrimStartAndEnd());
	OutRotator.Roll = FCString::Atof(*Parts[2].TrimStartAndEnd());
	return true;
}

bool CPBParseBoolCell(const FString& InValue, bool bDefaultValue)
{
	const FString CleanValue = CPBCleanCell(InValue);
	if (CleanValue.IsEmpty())
	{
		return bDefaultValue;
	}

	return CleanValue.Equals(TEXT("true"), ESearchCase::IgnoreCase) ||
		CleanValue.Equals(TEXT("1")) ||
		CleanValue.Equals(TEXT("yes"), ESearchCase::IgnoreCase) ||
		CleanValue.Equals(TEXT("y"), ESearchCase::IgnoreCase);
}

FString CPBJoinPackagePath(const FString& InFolder, const FString& AssetName)
{
	FString Folder = InFolder;
	Folder.TrimStartAndEndInline();
	Folder.ReplaceInline(TEXT("\\"), TEXT("/"));

	while (Folder.EndsWith(TEXT("/")))
	{
		Folder.LeftChopInline(1);
	}

	return Folder / AssetName;
}

bool CPBReadCsvRecords(const FString& CsvFilePath, TArray<FCPBCsvRecord>& OutRecords)
{
	OutRecords.Reset();

	FString CsvContent;
	if (!FFileHelper::LoadFileToString(CsvContent, *CsvFilePath))
	{
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB master CSV read failed: '%s'."), *CsvFilePath),
			ECPBEditorAutomationMessageType::Error);
		return false;
	}

	FCsvParser Parser(CsvContent);
	const TArray<TArray<const TCHAR*>>& ParsedRows = Parser.GetRows();

	int32 HeaderRowIndex = INDEX_NONE;
	TArray<FString> Headers;

	for (int32 RowIndex = 0; RowIndex < ParsedRows.Num(); ++RowIndex)
	{
		if (ParsedRows[RowIndex].Num() == 0)
		{
			continue;
		}

		const FString FirstHeaderCandidate = CPBNormalizeHeader(FString(ParsedRows[RowIndex][0]));
		if (FirstHeaderCandidate.Equals(TEXT("ID"), ESearchCase::IgnoreCase) ||
			FirstHeaderCandidate.Equals(TEXT("EventID"), ESearchCase::IgnoreCase) ||
			FirstHeaderCandidate.Equals(TEXT("StringID"), ESearchCase::IgnoreCase))
		{
			HeaderRowIndex = RowIndex;
			for (const TCHAR* Cell : ParsedRows[RowIndex])
			{
				Headers.Add(CPBNormalizeHeader(FString(Cell)));
			}
			break;
		}
	}

	if (HeaderRowIndex == INDEX_NONE || Headers.Num() == 0)
	{
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB master CSV parse failed: header row not found in '%s'."), *CsvFilePath),
			ECPBEditorAutomationMessageType::Error);
		return false;
	}

	for (int32 RowIndex = HeaderRowIndex + 1; RowIndex < ParsedRows.Num(); ++RowIndex)
	{
		const TArray<const TCHAR*>& ParsedRow = ParsedRows[RowIndex];

		bool bHasAnyValue = false;
		FCPBCsvRecord Record;

		for (int32 ColumnIndex = 0; ColumnIndex < Headers.Num(); ++ColumnIndex)
		{
			const FString Header = Headers[ColumnIndex];
			if (Header.IsEmpty())
			{
				continue;
			}

			const FString Value = ParsedRow.IsValidIndex(ColumnIndex) ? FString(ParsedRow[ColumnIndex]) : FString();
			if (!CPBCleanCell(Value).IsEmpty())
			{
				bHasAnyValue = true;
			}

			Record.Cells.Add(Header, Value);
		}

		if (!bHasAnyValue)
		{
			continue;
		}

		FString RowNameValue = CPBGetCell(Record, TEXT("ID"));
		if (RowNameValue.IsEmpty())
		{
			RowNameValue = CPBGetCell(Record, TEXT("EventID"));
		}
		if (RowNameValue.IsEmpty())
		{
			RowNameValue = CPBGetCell(Record, TEXT("StringID"));
		}

		Record.RowName = RowNameValue.IsEmpty()
			? FName(*FString::Printf(TEXT("Row_%d"), RowIndex + 1))
			: FName(*RowNameValue);

		OutRecords.Add(MoveTemp(Record));
	}

	return true;
}

UDataTable* CPBCreateOrUpdateDataTable(const FString& DestinationAssetFolder, const FString& AssetName, UScriptStruct* RowStruct)
{
	if (!RowStruct)
	{
		return nullptr;
	}

	const FString PackageName = CPBJoinPackagePath(DestinationAssetFolder, AssetName);
	if (!FPackageName::IsValidLongPackageName(PackageName))
	{
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB DataTable asset path is invalid: '%s'."), *PackageName),
			ECPBEditorAutomationMessageType::Error);
		return nullptr;
	}

	const FString ObjectPath = PackageName + TEXT(".") + AssetName;
	UDataTable* DataTable = LoadObject<UDataTable>(nullptr, *ObjectPath);

	if (!DataTable)
	{
		UPackage* Package = CreatePackage(*PackageName);
		DataTable = NewObject<UDataTable>(Package, *AssetName, RF_Public | RF_Standalone | RF_Transactional);
		DataTable->RowStruct = RowStruct;
		FAssetRegistryModule::AssetCreated(DataTable);
	}
	else if (DataTable->GetRowStruct() != RowStruct)
	{
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB DataTable update failed: '%s' uses '%s', expected '%s'."),
				*DataTable->GetName(),
				DataTable->GetRowStruct() ? *DataTable->GetRowStruct()->GetName() : TEXT("None"),
				*RowStruct->GetName()),
			ECPBEditorAutomationMessageType::Error);
		return nullptr;
	}

	DataTable->Modify();
	DataTable->RowStruct = RowStruct;
	DataTable->EmptyTable();
	DataTable->MarkPackageDirty();
	return DataTable;
}

UClass* CPBLoadClassByPath(const FString& ClassPath)
{
	if (ClassPath.IsEmpty())
	{
		return nullptr;
	}

	UClass* LoadedClass = LoadObject<UClass>(nullptr, *ClassPath);
	if (!LoadedClass && !ClassPath.EndsWith(TEXT("_C")))
	{
		LoadedClass = LoadObject<UClass>(nullptr, *(ClassPath + TEXT("_C")));
	}

	return LoadedClass;
}

UClass* CPBFindBlueprintClassByAssetName(const FString& AssetName)
{
	if (AssetName.IsEmpty())
	{
		return nullptr;
	}

	FAssetRegistryModule& AssetRegistryModule = FModuleManager::LoadModuleChecked<FAssetRegistryModule>(TEXT("AssetRegistry"));

	FARFilter Filter;
	Filter.bRecursivePaths = true;
	Filter.PackagePaths.Add(FName(TEXT("/cppBuilderC")));

	TArray<FAssetData> AssetDataList;
	AssetRegistryModule.Get().GetAssets(Filter, AssetDataList);

	for (const FAssetData& AssetData : AssetDataList)
	{
		if (!AssetData.AssetName.ToString().Equals(AssetName, ESearchCase::IgnoreCase))
		{
			continue;
		}

		FString GeneratedClassPath;
		if (AssetData.GetTagValue(TEXT("GeneratedClass"), GeneratedClassPath))
		{
			const FString ClassObjectPath = FPackageName::ExportTextPathToObjectPath(GeneratedClassPath);
			if (UClass* BlueprintClass = LoadObject<UClass>(nullptr, *ClassObjectPath))
			{
				return BlueprintClass;
			}
		}
	}

	return nullptr;
}

UClass* CPBResolveActorClass(const FString& ActorClassValue)
{
	const FString CleanClassValue = CPBCleanCell(ActorClassValue);
	if (CleanClassValue.IsEmpty())
	{
		return nullptr;
	}

	if (CleanClassValue.Contains(TEXT("/")))
	{
		if (UClass* LoadedPathClass = CPBLoadClassByPath(CleanClassValue))
		{
			return LoadedPathClass;
		}
	}

	if (CleanClassValue.Equals(TEXT("ACPBInteractorBase"), ESearchCase::IgnoreCase))
	{
		if (UClass* PreferredBlueprint = CPBLoadClassByPath(TEXT("/cppBuilderC/BP/BP_Interactor.BP_Interactor_C")))
		{
			return PreferredBlueprint;
		}

		return ACPBInteractorBase::StaticClass();
	}

	if (CleanClassValue.Equals(TEXT("ACPBSequenceManager"), ESearchCase::IgnoreCase))
	{
		if (UClass* PreferredBlueprint = CPBLoadClassByPath(TEXT("/cppBuilderC/BP/BP_SequenceManager.BP_SequenceManager_C")))
		{
			return PreferredBlueprint;
		}

		return ACPBSequenceManager::StaticClass();
	}

	if (CleanClassValue.Equals(TEXT("ACPBSequence"), ESearchCase::IgnoreCase))
	{
		if (UClass* PreferredBlueprint = CPBLoadClassByPath(TEXT("/cppBuilderC/BP/BP_Sequence.BP_Sequence_C")))
		{
			return PreferredBlueprint;
		}

		return ACPBSequence::StaticClass();
	}

	if (CleanClassValue.Equals(TEXT("AActor"), ESearchCase::IgnoreCase))
	{
		return AActor::StaticClass();
	}

	if (UClass* BlueprintClass = CPBFindBlueprintClassByAssetName(CleanClassValue))
	{
		return BlueprintClass;
	}

	FString NativeClassName = CleanClassValue;
	if ((NativeClassName.StartsWith(TEXT("A")) || NativeClassName.StartsWith(TEXT("U"))) && NativeClassName.Len() > 1)
	{
		NativeClassName.RightChopInline(1);
	}

	return CPBLoadClassByPath(FString::Printf(TEXT("/Script/cppBuilderC.%s"), *NativeClassName));
}

USoundBase* CPBResolveSoundAsset(const FString& AssetNameValue, const FString& AssetRootPath)
{
	const FString AssetName = CPBCleanCell(AssetNameValue);
	if (AssetName.IsEmpty())
	{
		return nullptr;
	}

	FString RootPath = AssetRootPath;
	RootPath.TrimStartAndEndInline();
	RootPath.ReplaceInline(TEXT("\\"), TEXT("/"));
	while (RootPath.EndsWith(TEXT("/")))
	{
		RootPath.LeftChopInline(1);
	}

	if (!RootPath.IsEmpty())
	{
		const FString DirectObjectPath = RootPath / AssetName + TEXT(".") + AssetName;
		if (USoundBase* DirectSound = LoadObject<USoundBase>(nullptr, *DirectObjectPath))
		{
			return DirectSound;
		}
	}

	FAssetRegistryModule& AssetRegistryModule = FModuleManager::LoadModuleChecked<FAssetRegistryModule>(TEXT("AssetRegistry"));
	FARFilter Filter;
	Filter.bRecursivePaths = true;
	if (!RootPath.IsEmpty())
	{
		Filter.PackagePaths.Add(FName(*RootPath));
	}
	else
	{
		Filter.PackagePaths.Add(FName(TEXT("/cppBuilderC")));
	}

	TArray<FAssetData> AssetDataList;
	AssetRegistryModule.Get().GetAssets(Filter, AssetDataList);
	for (const FAssetData& AssetData : AssetDataList)
	{
		if (!AssetData.AssetName.ToString().Equals(AssetName, ESearchCase::IgnoreCase))
		{
			continue;
		}

		if (USoundBase* Sound = Cast<USoundBase>(AssetData.GetAsset()))
		{
			return Sound;
		}
	}

	return nullptr;
}

AActor* CPBFindActorByTag(UWorld* World, FName ActorTag)
{
	if (!World || ActorTag.IsNone())
	{
		return nullptr;
	}

	for (TActorIterator<AActor> ActorIt(World); ActorIt; ++ActorIt)
	{
		AActor* Actor = *ActorIt;
		if (Actor && Actor->Tags.Contains(ActorTag))
		{
			return Actor;
		}
	}

	return nullptr;
}

bool CPBHasAnyTagWithPrefix(const AActor* Actor, const FString& Prefix)
{
	if (!Actor)
	{
		return false;
	}

	for (const FName& Tag : Actor->Tags)
	{
		if (Tag.ToString().StartsWith(Prefix))
		{
			return true;
		}
	}

	return false;
}

bool CPBIsLegacyAutoGeneratedActor(const AActor* Actor)
{
	if (!Actor)
	{
		return false;
	}

	const FString ActorLabel = Actor->GetActorLabel();
	if (ActorLabel.Equals(TEXT("CPB_SequenceManager_Auto"), ESearchCase::IgnoreCase) &&
		Actor->IsA<ACPBSequenceManager>())
	{
		return true;
	}

	if (ActorLabel.StartsWith(TEXT("SEQ_")) && Actor->IsA<ACPBSequence>())
	{
		return true;
	}

	if (ActorLabel.StartsWith(TEXT("SPW_")) &&
		(Actor->IsA<ACPBInteractorBase>() || Actor->IsA<ACPBSequenceManager>() || CPBHasAnyTagWithPrefix(Actor, TEXT("Tag_"))))
	{
		return true;
	}

	return false;
}

bool CPBShouldCleanupActor(const AActor* Actor)
{
	return Actor &&
		(Actor->Tags.Contains(CPBAutoGeneratedActorTag) || CPBIsLegacyAutoGeneratedActor(Actor));
}

ACPBSequenceManager* CPBFindOrSpawnSequenceManager(UWorld* World)
{
	if (!World)
	{
		return nullptr;
	}

	for (TActorIterator<ACPBSequenceManager> ManagerIt(World); ManagerIt; ++ManagerIt)
	{
		if (ACPBSequenceManager* Manager = *ManagerIt)
		{
			if (Manager->Tags.Contains(TEXT("Tag_SeqManager")))
			{
				return Manager;
			}
		}
	}

	for (TActorIterator<ACPBSequenceManager> ManagerIt(World); ManagerIt; ++ManagerIt)
	{
		return *ManagerIt;
	}

	UClass* ManagerClass = CPBResolveActorClass(TEXT("ACPBSequenceManager"));
	if (!ManagerClass || !ManagerClass->IsChildOf(ACPBSequenceManager::StaticClass()))
	{
		return nullptr;
	}

	FActorSpawnParameters SpawnParameters;
	SpawnParameters.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
	SpawnParameters.ObjectFlags |= RF_Transactional;

	ACPBSequenceManager* SpawnedManager = World->SpawnActor<ACPBSequenceManager>(ManagerClass, FVector::ZeroVector, FRotator::ZeroRotator, SpawnParameters);
	if (SpawnedManager)
	{
		SpawnedManager->Tags.AddUnique(CPBAutoGeneratedActorTag);
		SpawnedManager->Tags.AddUnique(CPBAutomationSystemTag);
		SpawnedManager->Tags.Add(FName(TEXT("Tag_SeqManager")));
		SpawnedManager->SetActorLabel(TEXT("CPB_SequenceManager_Auto"));
	}

	return SpawnedManager;
}

bool CPBSetFNameProperty(UObject* Object, FName PropertyName, FName Value)
{
	if (!Object)
	{
		return false;
	}

	if (FNameProperty* Property = FindFProperty<FNameProperty>(Object->GetClass(), PropertyName))
	{
		Object->Modify();
		Property->SetPropertyValue_InContainer(Object, Value);
		return true;
	}

	return false;
}

bool CPBSetFTextProperty(UObject* Object, FName PropertyName, const FText& Value)
{
	if (!Object)
	{
		return false;
	}

	if (FTextProperty* Property = FindFProperty<FTextProperty>(Object->GetClass(), PropertyName))
	{
		Object->Modify();
		Property->SetPropertyValue_InContainer(Object, Value);
		return true;
	}

	return false;
}

bool CPBSetIntProperty(UObject* Object, FName PropertyName, int32 Value)
{
	if (!Object)
	{
		return false;
	}

	if (FIntProperty* Property = FindFProperty<FIntProperty>(Object->GetClass(), PropertyName))
	{
		Object->Modify();
		Property->SetPropertyValue_InContainer(Object, Value);
		return true;
	}

	return false;
}

bool CPBSetSequenceSteps(ACPBSequence* Sequence, const TArray<FCPBSequenceStep>& Steps)
{
	if (!Sequence)
	{
		return false;
	}

	FArrayProperty* StepsProperty = FindFProperty<FArrayProperty>(Sequence->GetClass(), TEXT("Steps"));
	if (!StepsProperty)
	{
		return false;
	}

	FStructProperty* InnerStructProperty = CastField<FStructProperty>(StepsProperty->Inner);
	if (!InnerStructProperty || InnerStructProperty->Struct != FCPBSequenceStep::StaticStruct())
	{
		return false;
	}

	Sequence->Modify();
	void* ArrayPtr = StepsProperty->ContainerPtrToValuePtr<void>(Sequence);
	FScriptArrayHelper ArrayHelper(StepsProperty, ArrayPtr);
	ArrayHelper.EmptyValues();

	for (const FCPBSequenceStep& Step : Steps)
	{
		const int32 NewIndex = ArrayHelper.AddValue();
		void* DestinationPtr = ArrayHelper.GetRawPtr(NewIndex);
		InnerStructProperty->CopySingleValue(DestinationPtr, &Step);
	}

	return true;
}

bool CPBBuildGeneratedDataTables(
	const FString& CsvFolderPath,
	const FString& DestinationAssetFolder,
	const FString& NarrationAssetRootPath,
	FCPBGeneratedDataTables& OutGeneratedTables)
{
	const FString FullCsvFolderPath = FPaths::ConvertRelativePathToFull(CsvFolderPath);
	if (!FPaths::DirectoryExists(FullCsvFolderPath))
	{
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB master automation failed: CSV folder does not exist at '%s'."), *FullCsvFolderPath),
			ECPBEditorAutomationMessageType::Error);
		return false;
	}

	TArray<FCPBCsvRecord> LevelRecords;
	TArray<FCPBCsvRecord> ScenarioFlowRecords;
	TArray<FCPBCsvRecord> ActionEventRecords;
	TArray<FCPBCsvRecord> DictionaryRecords;

	const bool bReadLevel = CPBReadCsvRecords(FPaths::Combine(FullCsvFolderPath, TEXT("Set_Level.csv")), LevelRecords);
	const bool bReadScenarioFlow = CPBReadCsvRecords(FPaths::Combine(FullCsvFolderPath, TEXT("DT_ScenarioFlow.csv")), ScenarioFlowRecords);
	const bool bReadActionEvents = CPBReadCsvRecords(FPaths::Combine(FullCsvFolderPath, TEXT("DT_ActionEvent.csv")), ActionEventRecords);
	const bool bReadDictionary = CPBReadCsvRecords(FPaths::Combine(FullCsvFolderPath, TEXT("DT_Dictionary.csv")), DictionaryRecords);

	if (!bReadLevel || !bReadScenarioFlow)
	{
		return false;
	}

	OutGeneratedTables.LevelPlacementTable = CPBCreateOrUpdateDataTable(DestinationAssetFolder, TEXT("DT_CPB_LevelPlacement_Auto"), FCPBLevelPlacementDTO::StaticStruct());
	OutGeneratedTables.ScenarioFlowTable = CPBCreateOrUpdateDataTable(DestinationAssetFolder, TEXT("DT_CPB_ScenarioFlow_Auto"), FCPBScenarioFlowDTO::StaticStruct());
	OutGeneratedTables.ActionEventTable = CPBCreateOrUpdateDataTable(DestinationAssetFolder, TEXT("DT_CPB_ActionEvent_Auto"), FCPBActionEventDTO::StaticStruct());
	OutGeneratedTables.DictionaryTable = CPBCreateOrUpdateDataTable(DestinationAssetFolder, TEXT("DT_CPB_Dictionary_Auto"), FCPBDictionaryDTO::StaticStruct());
	OutGeneratedTables.ScenarioTable = CPBCreateOrUpdateDataTable(DestinationAssetFolder, TEXT("DT_CPB_Scenario_Auto"), FCPBScenarioDTO::StaticStruct());
	OutGeneratedTables.StringTable = CPBCreateOrUpdateDataTable(DestinationAssetFolder, TEXT("DT_CPB_String_Auto"), FCPBStringDTO::StaticStruct());
	OutGeneratedTables.SoundTable = CPBCreateOrUpdateDataTable(DestinationAssetFolder, TEXT("DT_CPB_Sound_Auto"), FCPBSoundDTO::StaticStruct());
	OutGeneratedTables.NarrationTable = CPBCreateOrUpdateDataTable(DestinationAssetFolder, TEXT("DT_CPB_Narration_Auto"), FCPBNarrationDTO::StaticStruct());

	if (!OutGeneratedTables.LevelPlacementTable ||
		!OutGeneratedTables.ScenarioFlowTable ||
		!OutGeneratedTables.ActionEventTable ||
		!OutGeneratedTables.DictionaryTable ||
		!OutGeneratedTables.ScenarioTable ||
		!OutGeneratedTables.StringTable ||
		!OutGeneratedTables.SoundTable ||
		!OutGeneratedTables.NarrationTable)
	{
		return false;
	}

	for (const FCPBCsvRecord& Record : LevelRecords)
	{
		FCPBLevelPlacementDTO Row;
		if (UClass* ActorClass = CPBResolveActorClass(CPBGetCell(Record, TEXT("ActorClass"))))
		{
			Row.ActorClass = TSoftClassPtr<AActor>(FSoftObjectPath(ActorClass));
		}
		else
		{
			CPBReportAutomationMessage(
				FString::Printf(TEXT("CPB level placement row '%s': actor class '%s' could not be resolved."),
					*Record.RowName.ToString(),
					*CPBGetCell(Record, TEXT("ActorClass"))),
				ECPBEditorAutomationMessageType::Warning);
		}

		Row.ActorTag = CPBNameFromCell(CPBGetCell(Record, TEXT("ActorTag")));
		CPBTryParseVectorCell(CPBGetCell(Record, TEXT("Location")), Row.Location);
		CPBTryParseRotatorCell(CPBGetCell(Record, TEXT("Rotation")), Row.Rotation);
		Row.InitialVisible = CPBParseBoolCell(CPBGetCell(Record, TEXT("InitialVisible")), true);
		OutGeneratedTables.LevelPlacementTable->AddRow(Record.RowName, Row);
	}

	TArray<FCPBScenarioFlowDTO> ScenarioRows;
	for (const FCPBCsvRecord& Record : ScenarioFlowRecords)
	{
		FCPBScenarioFlowDTO Row;
		Row.SequenceId = Record.RowName;
		Row.PhaseId = CPBNameFromCell(CPBGetCell(Record, TEXT("PhaseID")));
		Row.PhaseName = FText::FromString(CPBGetCell(Record, TEXT("PhaseName")));
		Row.StepOrder = FCString::Atoi(*CPBGetCell(Record, TEXT("StepOrder")));
		Row.TargetViewTag = CPBNameFromCell(CPBGetCell(Record, TEXT("TargetViewTag")));
		Row.TargetInteractorTag = CPBNameFromCell(CPBGetCell(Record, TEXT("TargetInteractorTag")));
		Row.RequiredToolName = CPBNameFromCell(CPBGetCell(Record, TEXT("RequiredTool_Name")));
		Row.InteractionType = CPBNameFromCell(CPBGetCell(Record, TEXT("InteractionType")));

		ScenarioRows.Add(Row);
		OutGeneratedTables.ScenarioFlowTable->AddRow(Record.RowName, Row);
	}

	ScenarioRows.Sort([](const FCPBScenarioFlowDTO& Left, const FCPBScenarioFlowDTO& Right)
	{
		if (Left.PhaseId == Right.PhaseId)
		{
			return Left.StepOrder < Right.StepOrder;
		}

		return Left.PhaseId.LexicalLess(Right.PhaseId);
	});

	TMap<FName, FCPBScenarioDTO> ScenarioByPhase;
	for (const FCPBScenarioFlowDTO& ScenarioRow : ScenarioRows)
	{
		if (ScenarioRow.PhaseId.IsNone() || ScenarioRow.SequenceId.IsNone())
		{
			continue;
		}

		FCPBScenarioDTO& Scenario = ScenarioByPhase.FindOrAdd(ScenarioRow.PhaseId);
		Scenario.ScenarioId = ScenarioRow.PhaseId;
		Scenario.GameMode = ECPBGameMode::Practice;
		Scenario.DisplayName = ScenarioRow.PhaseName;
		Scenario.DefaultLanguage = ECPBLanguage::Korean;
		Scenario.SequenceIds.Add(ScenarioRow.SequenceId);
	}

	for (const TPair<FName, FCPBScenarioDTO>& ScenarioPair : ScenarioByPhase)
	{
		OutGeneratedTables.ScenarioTable->AddRow(ScenarioPair.Key, ScenarioPair.Value);
	}

	for (const FCPBCsvRecord& Record : ActionEventRecords)
	{
		FCPBActionEventDTO Row;
		Row.EventId = Record.RowName;
		Row.OwnerSequence = CPBNameFromCell(CPBGetCell(Record, TEXT("OwnerSequence")));
		Row.Trigger = CPBNameFromCell(CPBGetCell(Record, TEXT("Trigger")));
		Row.Time = FCString::Atof(*CPBGetCell(Record, TEXT("Time")));
		Row.ActionType = CPBNameFromCell(CPBGetCell(Record, TEXT("ActionType")));
		Row.TargetTag = CPBNameFromCell(CPBGetCell(Record, TEXT("TargetTag")));
		Row.AssetName = CPBNameFromCell(CPBGetCell(Record, TEXT("Asset_Name")));
		Row.NarrationKOR = FText::FromString(CPBGetCell(Record, TEXT("Narration_KOR")));
		OutGeneratedTables.ActionEventTable->AddRow(Record.RowName, Row);

		if (!Row.AssetName.IsNone())
		{
			FCPBSoundDTO SoundRow;
			SoundRow.SoundId = Row.AssetName;
			SoundRow.Language = ECPBLanguage::Korean;
			if (USoundBase* Sound = CPBResolveSoundAsset(Row.AssetName.ToString(), NarrationAssetRootPath))
			{
				SoundRow.Sound = Sound;
			}
			OutGeneratedTables.SoundTable->AddRow(FName(*FString::Printf(TEXT("%s_KOR"), *Row.AssetName.ToString())), SoundRow);
		}

		if (Row.ActionType == FName(TEXT("PlayNarration")) || !Row.NarrationKOR.IsEmpty())
		{
			FCPBNarrationDTO NarrationRow;
			NarrationRow.NarrationId = Row.EventId;
			NarrationRow.SequenceId = Row.OwnerSequence;
			NarrationRow.StepIndex = 0;
			NarrationRow.SubtitleOverride = Row.NarrationKOR;
			if (!Row.AssetName.IsNone())
			{
				if (USoundBase* Sound = CPBResolveSoundAsset(Row.AssetName.ToString(), NarrationAssetRootPath))
				{
					NarrationRow.NarrationSound = Sound;
				}
				else
				{
					CPBReportAutomationMessage(
						FString::Printf(TEXT("CPB narration row '%s': sound asset '%s' was not found under '%s'."),
							*Row.EventId.ToString(),
							*Row.AssetName.ToString(),
							*NarrationAssetRootPath),
						ECPBEditorAutomationMessageType::Warning);
				}
			}
			NarrationRow.bAutoAdvanceSequenceOnFinished = true;
			OutGeneratedTables.NarrationTable->AddRow(Row.EventId, NarrationRow);
		}
	}

	for (const FCPBCsvRecord& Record : DictionaryRecords)
	{
		FCPBDictionaryDTO DictionaryRow;
		DictionaryRow.StringId = CPBNameFromCell(CPBGetCell(Record, TEXT("StringID")));
		DictionaryRow.KOR = FText::FromString(CPBGetCell(Record, TEXT("KOR")));
		DictionaryRow.ENG = FText::FromString(CPBGetCell(Record, TEXT("ENG")));
		OutGeneratedTables.DictionaryTable->AddRow(Record.RowName, DictionaryRow);

		if (!DictionaryRow.StringId.IsNone() && !DictionaryRow.KOR.IsEmpty())
		{
			FCPBStringDTO StringRow;
			StringRow.StringId = DictionaryRow.StringId;
			StringRow.Language = ECPBLanguage::Korean;
			StringRow.Text = DictionaryRow.KOR;
			OutGeneratedTables.StringTable->AddRow(FName(*FString::Printf(TEXT("%s_KOR"), *DictionaryRow.StringId.ToString())), StringRow);
		}

		if (!DictionaryRow.StringId.IsNone() && !DictionaryRow.ENG.IsEmpty())
		{
			FCPBStringDTO StringRow;
			StringRow.StringId = DictionaryRow.StringId;
			StringRow.Language = ECPBLanguage::English;
			StringRow.Text = DictionaryRow.ENG;
			OutGeneratedTables.StringTable->AddRow(FName(*FString::Printf(TEXT("%s_ENG"), *DictionaryRow.StringId.ToString())), StringRow);
		}
	}

	TArray<UDataTable*> TablesToBroadcast =
	{
		OutGeneratedTables.LevelPlacementTable,
		OutGeneratedTables.ScenarioFlowTable,
		OutGeneratedTables.ActionEventTable,
		OutGeneratedTables.DictionaryTable,
		OutGeneratedTables.ScenarioTable,
		OutGeneratedTables.StringTable,
		OutGeneratedTables.SoundTable,
		OutGeneratedTables.NarrationTable
	};

	for (UDataTable* DataTable : TablesToBroadcast)
	{
		if (DataTable)
		{
			FDataTableEditorUtils::BroadcastPostChange(DataTable, FDataTableEditorUtils::EDataTableChangeInfo::RowList);
			DataTable->MarkPackageDirty();
		}
	}

	return true;
}
}

bool UCPBEditorAutomationBFL::ImportCSVToDataTable(const FString& CsvFilePath, UDataTable* TargetDataTable)
{
	if (!TargetDataTable)
	{
		CPBReportAutomationMessage(TEXT("CPB CSV import failed: TargetDataTable is null."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	if (!TargetDataTable->GetRowStruct())
	{
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB CSV import failed: DataTable '%s' has no row struct."), *TargetDataTable->GetName()),
			ECPBEditorAutomationMessageType::Error);
		return false;
	}

	const FString FullCsvFilePath = FPaths::ConvertRelativePathToFull(CsvFilePath);
	if (!FPaths::FileExists(FullCsvFilePath))
	{
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB CSV import failed: CSV file does not exist at '%s'."), *FullCsvFilePath),
			ECPBEditorAutomationMessageType::Error);
		return false;
	}

	FString CsvContent;
	if (!FFileHelper::LoadFileToString(CsvContent, *FullCsvFilePath))
	{
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB CSV import failed: Could not read '%s'."), *FullCsvFilePath),
			ECPBEditorAutomationMessageType::Error);
		return false;
	}

	const FScopedTransaction Transaction(NSLOCTEXT("CPBEditorAutomation", "ImportCSVToDataTable", "Import CPB CSV To DataTable"));
	TargetDataTable->Modify();

	FDataTableEditorUtils::BroadcastPreChange(TargetDataTable, FDataTableEditorUtils::EDataTableChangeInfo::RowList);
	const TArray<FString> ImportProblems = TargetDataTable->CreateTableFromCSVString(CsvContent);
	FDataTableEditorUtils::BroadcastPostChange(TargetDataTable, FDataTableEditorUtils::EDataTableChangeInfo::RowList);

	TargetDataTable->MarkPackageDirty();

	for (const FString& ImportProblem : ImportProblems)
	{
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB CSV import warning for '%s': %s"), *TargetDataTable->GetName(), *ImportProblem),
			ECPBEditorAutomationMessageType::Warning);
	}

	if (ImportProblems.Num() > 0)
	{
		return false;
	}

	CPBReportAutomationMessage(
		FString::Printf(TEXT("CPB CSV import completed: '%s' updated from '%s'."), *TargetDataTable->GetName(), *FullCsvFilePath),
		ECPBEditorAutomationMessageType::Info);
	return true;
}

bool UCPBEditorAutomationBFL::AutoGenerateLevelFromDataTable(UDataTable* LevelPlacementTable)
{
	if (!LevelPlacementTable)
	{
		CPBReportAutomationMessage(TEXT("CPB level generation failed: LevelPlacementTable is null."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	if (LevelPlacementTable->GetRowStruct() != FCPBLevelPlacementDTO::StaticStruct())
	{
		const FString ActualStructName = LevelPlacementTable->GetRowStruct()
			? LevelPlacementTable->GetRowStruct()->GetName()
			: TEXT("None");

		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB level generation failed: DataTable '%s' uses row struct '%s' instead of FCPBLevelPlacementDTO."),
				*LevelPlacementTable->GetName(),
				*ActualStructName),
			ECPBEditorAutomationMessageType::Error);
		return false;
	}

	if (!GEditor)
	{
		CPBReportAutomationMessage(TEXT("CPB level generation failed: GEditor is unavailable."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	UWorld* World = GEditor->GetEditorWorldContext().World();
	if (!World)
	{
		CPBReportAutomationMessage(TEXT("CPB level generation failed: Editor world is unavailable."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	if (World->IsPlayInEditor() || GEditor->PlayWorld)
	{
		CPBReportAutomationMessage(TEXT("CPB level generation aborted: actor spawning is disabled while Play In Editor is active."), ECPBEditorAutomationMessageType::Warning);
		return false;
	}

	const TMap<FName, uint8*>& RowMap = LevelPlacementTable->GetRowMap();
	if (RowMap.Num() == 0)
	{
		CPBReportAutomationMessage(
			FString::Printf(TEXT("CPB level generation skipped: DataTable '%s' has no rows."), *LevelPlacementTable->GetName()),
			ECPBEditorAutomationMessageType::Warning);
		return false;
	}

	const FScopedTransaction Transaction(NSLOCTEXT("CPBEditorAutomation", "AutoGenerateLevelFromDataTable", "Auto Generate CPB Level From DataTable"));
	World->Modify();

	int32 SpawnedCount = 0;
	int32 FailedCount = 0;

	for (const TPair<FName, uint8*>& RowPair : RowMap)
	{
		const FName RowName = RowPair.Key;
		const FCPBLevelPlacementDTO* Row = reinterpret_cast<const FCPBLevelPlacementDTO*>(RowPair.Value);
		if (!Row)
		{
			++FailedCount;
			CPBReportAutomationMessage(
				FString::Printf(TEXT("CPB level generation failed for row '%s': row data is invalid."), *RowName.ToString()),
				ECPBEditorAutomationMessageType::Warning);
			continue;
		}

		UClass* ActorClass = Row->ActorClass.LoadSynchronous();
		if (!ActorClass || !ActorClass->IsChildOf(AActor::StaticClass()))
		{
			++FailedCount;
			CPBReportAutomationMessage(
				FString::Printf(TEXT("CPB level generation failed for row '%s': ActorClass is invalid or could not be loaded."), *RowName.ToString()),
				ECPBEditorAutomationMessageType::Warning);
			continue;
		}

		FActorSpawnParameters SpawnParameters;
		SpawnParameters.Name = NAME_None;
		SpawnParameters.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
		SpawnParameters.ObjectFlags |= RF_Transactional;

		AActor* SpawnedActor = World->SpawnActor<AActor>(ActorClass, Row->Location, Row->Rotation, SpawnParameters);
		if (!SpawnedActor)
		{
			++FailedCount;
			CPBReportAutomationMessage(
				FString::Printf(TEXT("CPB level generation failed for row '%s': SpawnActor returned null for class '%s'."),
					*RowName.ToString(),
					*ActorClass->GetName()),
				ECPBEditorAutomationMessageType::Warning);
			continue;
		}

		SpawnedActor->Modify();
		SpawnedActor->Tags.AddUnique(CPBAutoGeneratedActorTag);
		SpawnedActor->Tags.AddUnique(CPBAutomationSystemTag);
		if (!Row->ActorTag.IsNone())
		{
			SpawnedActor->Tags.Add(Row->ActorTag);
		}
		else
		{
			CPBReportAutomationMessage(
				FString::Printf(TEXT("CPB level generation warning for row '%s': ActorTag is None."), *RowName.ToString()),
				ECPBEditorAutomationMessageType::Warning);
		}

		SpawnedActor->SetActorHiddenInGame(!Row->InitialVisible);
		SpawnedActor->SetActorLabel(RowName.ToString());

		++SpawnedCount;
	}

	World->MarkPackageDirty();

	const ECPBEditorAutomationMessageType ResultType = FailedCount > 0
		? ECPBEditorAutomationMessageType::Warning
		: ECPBEditorAutomationMessageType::Info;

	CPBReportAutomationMessage(
		FString::Printf(TEXT("CPB level generation completed: %d actors spawned, %d rows failed."), SpawnedCount, FailedCount),
		ResultType);

	return FailedCount == 0 && SpawnedCount > 0;
}

bool UCPBEditorAutomationBFL::ClearAutoGeneratedLevelActors()
{
	if (!GEditor)
	{
		CPBReportAutomationMessage(TEXT("CPB cleanup failed: GEditor is unavailable."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	UWorld* World = GEditor->GetEditorWorldContext().World();
	if (!World)
	{
		CPBReportAutomationMessage(TEXT("CPB cleanup failed: Editor world is unavailable."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	if (World->IsPlayInEditor() || GEditor->PlayWorld)
	{
		CPBReportAutomationMessage(TEXT("CPB cleanup aborted: generated actor cleanup is disabled while Play In Editor is active."), ECPBEditorAutomationMessageType::Warning);
		return false;
	}

	TArray<AActor*> ActorsToDelete;
	for (TActorIterator<AActor> ActorIt(World); ActorIt; ++ActorIt)
	{
		AActor* Actor = *ActorIt;
		if (CPBShouldCleanupActor(Actor))
		{
			ActorsToDelete.Add(Actor);
		}
	}

	if (ActorsToDelete.Num() == 0)
	{
		CPBReportAutomationMessage(TEXT("CPB cleanup skipped: no current or legacy auto-generated actors were found."), ECPBEditorAutomationMessageType::Info);
		return true;
	}

	const FScopedTransaction Transaction(NSLOCTEXT("CPBEditorAutomation", "ClearAutoGeneratedLevelActors", "Clear CPB Auto Generated Level Actors"));
	World->Modify();

	int32 DeletedCount = 0;
	for (AActor* Actor : ActorsToDelete)
	{
		if (!Actor || Actor->IsPendingKillPending())
		{
			continue;
		}

		Actor->Modify();
		if (World->EditorDestroyActor(Actor, true))
		{
			++DeletedCount;
		}
	}

	World->MarkPackageDirty();

	CPBReportAutomationMessage(
		FString::Printf(TEXT("CPB cleanup completed: %d current/legacy auto-generated actors deleted."), DeletedCount),
		ECPBEditorAutomationMessageType::Info);

	return DeletedCount == ActorsToDelete.Num();
}

bool UCPBEditorAutomationBFL::GenerateDataTablesFromMasterCSVFolder(
	const FString& CsvFolderPath,
	const FString& DestinationAssetFolder,
	const FString& NarrationAssetRootPath)
{
	FCPBGeneratedDataTables GeneratedTables;
	if (!CPBBuildGeneratedDataTables(CsvFolderPath, DestinationAssetFolder, NarrationAssetRootPath, GeneratedTables))
	{
		return false;
	}

	CPBReportAutomationMessage(
		FString::Printf(TEXT("CPB master CSV import completed. DataTables were created/updated under '%s'."), *DestinationAssetFolder),
		ECPBEditorAutomationMessageType::Info);
	return true;
}

bool UCPBEditorAutomationBFL::GenerateDataTablesFromExcelFolder(
	const FString& ExcelFolderPath,
	const FString& DestinationAssetFolder,
	const FString& NarrationAssetRootPath)
{
	FString ExcelFilePath;
	if (!CPBFindLatestExcelFileInFolder(ExcelFolderPath, ExcelFilePath))
	{
		return false;
	}

	return GenerateDataTablesFromExcelFile(ExcelFilePath, DestinationAssetFolder, NarrationAssetRootPath);
}

bool UCPBEditorAutomationBFL::GenerateDataTablesFromExcelFile(
	const FString& ExcelFilePath,
	const FString& DestinationAssetFolder,
	const FString& NarrationAssetRootPath)
{
	FString GeneratedCsvFolderPath;
	if (!CPBConvertXlsxToMasterCsvFolder(ExcelFilePath, GeneratedCsvFolderPath))
	{
		return false;
	}

	return GenerateDataTablesFromMasterCSVFolder(GeneratedCsvFolderPath, DestinationAssetFolder, NarrationAssetRootPath);
}

bool UCPBEditorAutomationBFL::AutoGenerateSequencesFromDataTables(UDataTable* ScenarioFlowTable, UDataTable* ActionEventTable)
{
	if (!ScenarioFlowTable || ScenarioFlowTable->GetRowStruct() != FCPBScenarioFlowDTO::StaticStruct())
	{
		CPBReportAutomationMessage(TEXT("CPB sequence generation failed: ScenarioFlowTable must use FCPBScenarioFlowDTO."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	if (!ActionEventTable || ActionEventTable->GetRowStruct() != FCPBActionEventDTO::StaticStruct())
	{
		CPBReportAutomationMessage(TEXT("CPB sequence generation failed: ActionEventTable must use FCPBActionEventDTO."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	if (!GEditor)
	{
		CPBReportAutomationMessage(TEXT("CPB sequence generation failed: GEditor is unavailable."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	UWorld* World = GEditor->GetEditorWorldContext().World();
	if (!World)
	{
		CPBReportAutomationMessage(TEXT("CPB sequence generation failed: Editor world is unavailable."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	if (World->IsPlayInEditor() || GEditor->PlayWorld)
	{
		CPBReportAutomationMessage(TEXT("CPB sequence generation aborted: sequence actor spawning is disabled while Play In Editor is active."), ECPBEditorAutomationMessageType::Warning);
		return false;
	}

	ACPBSequenceManager* SequenceManager = CPBFindOrSpawnSequenceManager(World);
	if (!SequenceManager)
	{
		CPBReportAutomationMessage(TEXT("CPB sequence generation failed: could not find or spawn ACPBSequenceManager."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	UClass* SequenceClass = CPBResolveActorClass(TEXT("ACPBSequence"));
	if (!SequenceClass || !SequenceClass->IsChildOf(ACPBSequence::StaticClass()))
	{
		CPBReportAutomationMessage(TEXT("CPB sequence generation failed: could not resolve ACPBSequence class."), ECPBEditorAutomationMessageType::Error);
		return false;
	}

	TArray<FCPBScenarioFlowDTO> ScenarioRows;
	for (const TPair<FName, uint8*>& RowPair : ScenarioFlowTable->GetRowMap())
	{
		const FCPBScenarioFlowDTO* Row = reinterpret_cast<const FCPBScenarioFlowDTO*>(RowPair.Value);
		if (Row && !Row->SequenceId.IsNone())
		{
			ScenarioRows.Add(*Row);
		}
	}

	ScenarioRows.Sort([](const FCPBScenarioFlowDTO& Left, const FCPBScenarioFlowDTO& Right)
	{
		if (Left.PhaseId == Right.PhaseId)
		{
			return Left.StepOrder < Right.StepOrder;
		}

		return Left.PhaseId.LexicalLess(Right.PhaseId);
	});

	TMultiMap<FName, FCPBActionEventDTO> EventsBySequence;
	for (const TPair<FName, uint8*>& RowPair : ActionEventTable->GetRowMap())
	{
		const FCPBActionEventDTO* Row = reinterpret_cast<const FCPBActionEventDTO*>(RowPair.Value);
		if (Row && !Row->OwnerSequence.IsNone())
		{
			EventsBySequence.Add(Row->OwnerSequence, *Row);
		}
	}

	const FScopedTransaction Transaction(NSLOCTEXT("CPBEditorAutomation", "AutoGenerateSequencesFromDataTables", "Auto Generate CPB Sequences From DataTables"));
	World->Modify();
	SequenceManager->Modify();

	int32 SpawnedSequenceCount = 0;
	int32 WarningCount = 0;

	for (const FCPBScenarioFlowDTO& ScenarioRow : ScenarioRows)
	{
		FActorSpawnParameters SpawnParameters;
		SpawnParameters.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
		SpawnParameters.ObjectFlags |= RF_Transactional;

		const FVector SpawnLocation = SequenceManager->GetActorLocation() + FVector(0.0f, SpawnedSequenceCount * 40.0f, 0.0f);
		ACPBSequence* Sequence = World->SpawnActor<ACPBSequence>(SequenceClass, SpawnLocation, SequenceManager->GetActorRotation(), SpawnParameters);
		if (!Sequence)
		{
			++WarningCount;
			CPBReportAutomationMessage(
				FString::Printf(TEXT("CPB sequence generation failed: could not spawn sequence '%s'."), *ScenarioRow.SequenceId.ToString()),
				ECPBEditorAutomationMessageType::Warning);
			continue;
		}

		Sequence->SetActorLabel(ScenarioRow.SequenceId.ToString());
		Sequence->Tags.AddUnique(CPBAutoGeneratedActorTag);
		Sequence->Tags.AddUnique(CPBAutomationSystemTag);
		Sequence->Tags.Add(ScenarioRow.SequenceId);
		Sequence->Tags.Add(ScenarioRow.PhaseId);

		CPBSetFNameProperty(Sequence, TEXT("SequenceId"), ScenarioRow.SequenceId);
		CPBSetFTextProperty(Sequence, TEXT("DisplayName"), FText::FromName(ScenarioRow.SequenceId));
		CPBSetIntProperty(Sequence, TEXT("SortOrder"), SpawnedSequenceCount);

		FCPBSequenceStep Step;
		Step.StepId = ScenarioRow.SequenceId;
		Step.CameraViewId = ScenarioRow.TargetViewTag;
		Step.ViewTransition = ECPBViewTransition::Fade;
		Step.FadeDuration = 0.25f;

		TArray<FCPBActionEventDTO> SequenceEvents;
		EventsBySequence.MultiFind(ScenarioRow.SequenceId, SequenceEvents);
		SequenceEvents.Sort([](const FCPBActionEventDTO& Left, const FCPBActionEventDTO& Right)
		{
			return Left.Time < Right.Time;
		});

		for (const FCPBActionEventDTO& EventRow : SequenceEvents)
		{
			Step.AnimationLength = FMath::Max(Step.AnimationLength, EventRow.Time);

			if (EventRow.ActionType == FName(TEXT("HideActor")) || EventRow.ActionType == FName(TEXT("ShowActor")))
			{
				AActor* TargetActor = CPBFindActorByTag(World, EventRow.TargetTag);
				if (!TargetActor)
				{
					++WarningCount;
					CPBReportAutomationMessage(
						FString::Printf(TEXT("CPB sequence '%s': target actor tag '%s' for event '%s' was not found."),
							*ScenarioRow.SequenceId.ToString(),
							*EventRow.TargetTag.ToString(),
							*EventRow.EventId.ToString()),
						ECPBEditorAutomationMessageType::Warning);
					continue;
				}

				if (EventRow.ActionType == FName(TEXT("HideActor")))
				{
					Step.HidingActors.AddUnique(TargetActor);
				}
				else
				{
					Step.UnhidingActors.AddUnique(TargetActor);
				}
			}
		}

		if (!CPBSetSequenceSteps(Sequence, { Step }))
		{
			++WarningCount;
			CPBReportAutomationMessage(
				FString::Printf(TEXT("CPB sequence '%s': failed to set generated step data."), *ScenarioRow.SequenceId.ToString()),
				ECPBEditorAutomationMessageType::Warning);
		}

		if (AActor* TargetInteractor = CPBFindActorByTag(World, ScenarioRow.TargetInteractorTag))
		{
			CPBSetFNameProperty(TargetInteractor, TEXT("AssemblyId"), ScenarioRow.SequenceId);

			if (!ScenarioRow.RequiredToolName.IsNone())
			{
				TargetInteractor->Tags.AddUnique(ScenarioRow.RequiredToolName);
			}

			if (!ScenarioRow.InteractionType.IsNone())
			{
				TargetInteractor->Tags.AddUnique(ScenarioRow.InteractionType);
			}
		}
		else if (!ScenarioRow.TargetInteractorTag.IsNone())
		{
			++WarningCount;
			CPBReportAutomationMessage(
				FString::Printf(TEXT("CPB sequence '%s': TargetInteractorTag '%s' was not found."),
					*ScenarioRow.SequenceId.ToString(),
					*ScenarioRow.TargetInteractorTag.ToString()),
				ECPBEditorAutomationMessageType::Warning);
		}

		SequenceManager->RegisterSequence(Sequence);
		++SpawnedSequenceCount;
	}

	SequenceManager->SortRegisteredSequencesBySortOrder();
	World->MarkPackageDirty();

	CPBReportAutomationMessage(
		FString::Printf(TEXT("CPB sequence generation completed: %d sequence actors created, %d warnings."), SpawnedSequenceCount, WarningCount),
		WarningCount > 0 ? ECPBEditorAutomationMessageType::Warning : ECPBEditorAutomationMessageType::Info);

	return SpawnedSequenceCount > 0;
}

bool UCPBEditorAutomationBFL::RunMasterAutomationFromCSVFolder(
	const FString& CsvFolderPath,
	const FString& DestinationAssetFolder,
	const FString& NarrationAssetRootPath)
{
	FCPBGeneratedDataTables GeneratedTables;
	if (!CPBBuildGeneratedDataTables(CsvFolderPath, DestinationAssetFolder, NarrationAssetRootPath, GeneratedTables))
	{
		return false;
	}

	ClearAutoGeneratedLevelActors();

	const bool bGeneratedLevel = AutoGenerateLevelFromDataTable(GeneratedTables.LevelPlacementTable);
	const bool bGeneratedSequences = AutoGenerateSequencesFromDataTables(GeneratedTables.ScenarioFlowTable, GeneratedTables.ActionEventTable);

	CPBReportAutomationMessage(
		FString::Printf(TEXT("CPB master automation completed: level=%s, sequences=%s, generated DataTables='%s'."),
			bGeneratedLevel ? TEXT("OK") : TEXT("Failed"),
			bGeneratedSequences ? TEXT("OK") : TEXT("Failed"),
			*DestinationAssetFolder),
		(bGeneratedLevel && bGeneratedSequences) ? ECPBEditorAutomationMessageType::Info : ECPBEditorAutomationMessageType::Warning);

	return bGeneratedLevel && bGeneratedSequences;
}

bool UCPBEditorAutomationBFL::RunMasterAutomationFromExcelFolder(
	const FString& ExcelFolderPath,
	const FString& DestinationAssetFolder,
	const FString& NarrationAssetRootPath)
{
	FString ExcelFilePath;
	if (!CPBFindLatestExcelFileInFolder(ExcelFolderPath, ExcelFilePath))
	{
		return false;
	}

	CPBReportAutomationMessage(
		FString::Printf(TEXT("CPB Excel automation selected workbook: '%s'."), *ExcelFilePath),
		ECPBEditorAutomationMessageType::Info);

	return RunMasterAutomationFromExcelFile(ExcelFilePath, DestinationAssetFolder, NarrationAssetRootPath);
}

bool UCPBEditorAutomationBFL::RunMasterAutomationFromExcelFile(
	const FString& ExcelFilePath,
	const FString& DestinationAssetFolder,
	const FString& NarrationAssetRootPath)
{
	FString GeneratedCsvFolderPath;
	if (!CPBConvertXlsxToMasterCsvFolder(ExcelFilePath, GeneratedCsvFolderPath))
	{
		return false;
	}

	CPBReportAutomationMessage(
		FString::Printf(TEXT("CPB Excel automation converted workbook to temporary CSV folder: '%s'."), *GeneratedCsvFolderPath),
		ECPBEditorAutomationMessageType::Info);

	return RunMasterAutomationFromCSVFolder(GeneratedCsvFolderPath, DestinationAssetFolder, NarrationAssetRootPath);
}
