// Copyright Epic Games, Inc. All Rights Reserved.
// Generated from TMLoc call sites. Do not edit manually.

#include "TMLocalization.h"

namespace
{
    void RegisterTMLocalizationTextKeys()
    {
        (void)NSLOCTEXT("TraceMotive", "!", "!");
        (void)NSLOCTEXT("TraceMotive", "## Actor-level findings", "## Actor-level findings");
        (void)NSLOCTEXT("TraceMotive", "## Evidence level and limitations", "## Evidence level and limitations");
        (void)NSLOCTEXT("TraceMotive", "## Quick fix tips", "## Quick fix tips");
        (void)NSLOCTEXT("TraceMotive", "## Suspicious movement nodes", "## Suspicious movement nodes");
        (void)NSLOCTEXT("TraceMotive", "*", "*");
        (void)NSLOCTEXT("TraceMotive", "-", "-");
        (void)NSLOCTEXT("TraceMotive", "- Actual movement can bypass collision through Sweep=false, Teleport, custom ignore lists, or MovementComponent UpdatedComponent/root mismatch.", "- Actual movement can bypass collision through Sweep=false, Teleport, custom ignore lists, or MovementComponent UpdatedComponent/root mismatch.");
        (void)NSLOCTEXT("TraceMotive", "- Best confirmation is a reproduced swept move with Sweep=true and the returned FHitResult.", "- Best confirmation is a reproduced swept move with Sweep=true and the returned FHitResult.");
        (void)NSLOCTEXT("TraceMotive", "- Block possible means settings are compatible with blocking; it is not proof that the real gameplay movement path blocks.", "- Block possible means settings are compatible with blocking; it is not proof that the real gameplay movement path blocks.");
        (void)NSLOCTEXT("TraceMotive", "- No obvious Sweep=false or Teleport movement node was found in the selected actors' Blueprint class chain.", "- No obvious Sweep=false or Teleport movement node was found in the selected actors' Blueprint class chain.");
        (void)NSLOCTEXT("TraceMotive", "- PhysicsOnly, Chaos contact resolution, complex BodySetup, and custom primitive collision cannot be fully proven by static/query inspection.", "- PhysicsOnly, Chaos contact resolution, complex BodySetup, and custom primitive collision cannot be fully proven by static/query inspection.");
        (void)NSLOCTEXT("TraceMotive", "->", "->");
        (void)NSLOCTEXT("TraceMotive", "...", "...");
        (void)NSLOCTEXT("TraceMotive", "00:00", "00:00");
        (void)NSLOCTEXT("TraceMotive", "<Invalid Event>", "<Invalid Event>");
        (void)NSLOCTEXT("TraceMotive", "<No Target>", "<No Target>");
        (void)NSLOCTEXT("TraceMotive", ">", ">");
        (void)NSLOCTEXT("TraceMotive", "A", "A");
        (void)NSLOCTEXT("TraceMotive", "A BLOCK-capable pair already exists and the sweep probe hit it. Usually no collision preset change is needed; if gameplay still passes through, check Sweep=true, Teleport=false, and custom ignore logic.", "A BLOCK-capable pair already exists and the sweep probe hit it. Usually no collision preset change is needed; if gameplay still passes through, check Sweep=true, Teleport=false, and custom ignore logic.");
        (void)NSLOCTEXT("TraceMotive", "A BLOCK-capable pair already exists. If gameplay still passes through, move the actor/component with Sweep=true, avoid Teleport, and make sure the movement component uses the blocking primitive as its UpdatedComponent/root collision.", "A BLOCK-capable pair already exists. If gameplay still passes through, move the actor/component with Sweep=true, avoid Teleport, and make sure the movement component uses the blocking primitive as its UpdatedComponent/root collision.");
        (void)NSLOCTEXT("TraceMotive", "A and B are the same actor", "A and B are the same actor");
        (void)NSLOCTEXT("TraceMotive", "A collision response is Ignore", "A collision response is Ignore");
        (void)NSLOCTEXT("TraceMotive", "A component", "A component");
        (void)NSLOCTEXT("TraceMotive", "Action: ", "Action: ");
        (void)NSLOCTEXT("TraceMotive", "Actions", "Actions");
        (void)NSLOCTEXT("TraceMotive", "Actions you can try now", "Actions you can try now");
        (void)NSLOCTEXT("TraceMotive", "Actor", "Actor");
        (void)NSLOCTEXT("TraceMotive", "Actor collision is disabled", "Actor collision is disabled");
        (void)NSLOCTEXT("TraceMotive", "Actor label, class, or path matched.", "Actor label, class, or path matched.");
        (void)NSLOCTEXT("TraceMotive", "Actor tag matched.", "Actor tag matched.");
        (void)NSLOCTEXT("TraceMotive", "Actor-level and movement checks", "Actor-level and movement checks");
        (void)NSLOCTEXT("TraceMotive", "Actors", "Actors");
        (void)NSLOCTEXT("TraceMotive", "Actors are in different worlds", "Actors are in different worlds");
        (void)NSLOCTEXT("TraceMotive", "Actors share an attachment hierarchy", "Actors share an attachment hierarchy");
        (void)NSLOCTEXT("TraceMotive", "Add or enable a PrimitiveComponent with collision, such as CapsuleComponent, BoxComponent, StaticMeshComponent, or BrushComponent.", "Add or enable a PrimitiveComponent with collision, such as CapsuleComponent, BoxComponent, StaticMeshComponent, or BrushComponent.");
        (void)NSLOCTEXT("TraceMotive", "Add selected placeable assets, Actor classes, or Levels to favorites.", "Add selected placeable assets, Actor classes, or Levels to favorites.");
        (void)NSLOCTEXT("TraceMotive", "Add to Asset & Level Favorites", "Add to Asset & Level Favorites");
        (void)NSLOCTEXT("TraceMotive", "Add to Investigation", "Add to Investigation");
        (void)NSLOCTEXT("TraceMotive", "All", "All");
        (void)NSLOCTEXT("TraceMotive", "All events", "All events");
        (void)NSLOCTEXT("TraceMotive", "All sources", "All sources");
        (void)NSLOCTEXT("TraceMotive", "Analysis could not start because one or both actors are invalid.", "Analysis could not start because one or both actors are invalid.");
        (void)NSLOCTEXT("TraceMotive", "Analyze", "Analyze");
        (void)NSLOCTEXT("TraceMotive", "Analyze Collision Between Selected", "Analyze Collision Between Selected");
        (void)NSLOCTEXT("TraceMotive", "Analyze latest log", "Analyze latest log");
        (void)NSLOCTEXT("TraceMotive", "Analyze the latest completed PIE log when live capture was not open.", "Analyze the latest completed PIE log when live capture was not open.");
        (void)NSLOCTEXT("TraceMotive", "Analyze why the two selected actors do not Block each other in Editor or PIE.", "Analyze why the two selected actors do not Block each other in Editor or PIE.");
        (void)NSLOCTEXT("TraceMotive", "Applies gameplay time dilation and audio pitch speed together for PIE/Game worlds.", "Applies gameplay time dilation and audio pitch speed together for PIE/Game worlds.");
        (void)NSLOCTEXT("TraceMotive", "Arm Skip to Target", "Arm Skip to Target");
        (void)NSLOCTEXT("TraceMotive", "Armed", "Armed");
        (void)NSLOCTEXT("TraceMotive", "Arms one PIE click, captures its direct Blueprint flow, then watches owner callbacks and bound OnClicked delegates for up to 10 seconds. Tick-like calls and repeats are filtered.", "Arms one PIE click, captures its direct Blueprint flow, then watches owner callbacks and bound OnClicked delegates for up to 10 seconds. Tick-like calls and repeats are filtered.");
        (void)NSLOCTEXT("TraceMotive", "Asset & Level Favorites", "Asset & Level Favorites");
        (void)NSLOCTEXT("TraceMotive", "Asset or Blueprint related failure", "Asset or Blueprint related failure");
        (void)NSLOCTEXT("TraceMotive", "Audio Playback Trace", "Audio Playback Trace");
        (void)NSLOCTEXT("TraceMotive", "Audio trace reset.", "Audio trace reset.");
        (void)NSLOCTEXT("TraceMotive", "Auto Snapshot", "Auto Snapshot");
        (void)NSLOCTEXT("TraceMotive", "Automatically detects editor packaging and estimates progress from UAT stages and work counts.", "Automatically detects editor packaging and estimates progress from UAT stages and work counts.");
        (void)NSLOCTEXT("TraceMotive", "Auxiliary", "Auxiliary");
        (void)NSLOCTEXT("TraceMotive", "B", "B");
        (void)NSLOCTEXT("TraceMotive", "B component", "B component");
        (void)NSLOCTEXT("TraceMotive", "Best confirmation: reproduce the move with Sweep=true and inspect the returned FHitResult, hit component, and blocking hit flag.", "Best confirmation: reproduce the move with Sweep=true and inspect the returned FHitResult, hit component, and blocking hit flag.");
        (void)NSLOCTEXT("TraceMotive", "Bindings found only in the selected or pointer-resolved target Blueprint and its relevant Level Blueprint.", "Bindings found only in the selected or pointer-resolved target Blueprint and its relevant Level Blueprint.");
        (void)NSLOCTEXT("TraceMotive", "Block impossible", "Block impossible");
        (void)NSLOCTEXT("TraceMotive", "Block possible means both components are configured to block. It does not prove that the real gameplay movement will be stopped.", "Block possible means both components are configured to block. It does not prove that the real gameplay movement will be stopped.");
        (void)NSLOCTEXT("TraceMotive", "Block-capable", "Block-capable");
        (void)NSLOCTEXT("TraceMotive", "Block-capable settings", "Block-capable settings");
        (void)NSLOCTEXT("TraceMotive", "Blocked", "Blocked");
        (void)NSLOCTEXT("TraceMotive", "Blueprint class", "Blueprint class");
        (void)NSLOCTEXT("TraceMotive", "Blueprint class event", "Blueprint class event");
        (void)NSLOCTEXT("TraceMotive", "Browse To Asset", "Browse To Asset");
        (void)NSLOCTEXT("TraceMotive", "CAUSE", "CAUSE");
        (void)NSLOCTEXT("TraceMotive", "CHECK", "CHECK");
        (void)NSLOCTEXT("TraceMotive", "Canceled", "Canceled");
        (void)NSLOCTEXT("TraceMotive", "Capture Selected", "Capture Selected");
        (void)NSLOCTEXT("TraceMotive", "Capture both actors from the same PIE/Game world. Editor-world and PIE-world actors cannot collide with each other.", "Capture both actors from the same PIE/Game world. Editor-world and PIE-world actors cannot collide with each other.");
        (void)NSLOCTEXT("TraceMotive", "Capture the short Blueprint function flow triggered by one PIE UMG click.", "Capture the short Blueprint function flow triggered by one PIE UMG click.");
        (void)NSLOCTEXT("TraceMotive", "Captured: {0}", "Captured: {0}");
        (void)NSLOCTEXT("TraceMotive", "Cause", "Cause");
        (void)NSLOCTEXT("TraceMotive", "Caution (4x-6x): use only outside physics, dense AI, complex UI animation, and networking-heavy sections.", "Caution (4x-6x): use only outside physics, dense AI, complex UI animation, and networking-heavy sections.");
        (void)NSLOCTEXT("TraceMotive", "Check", "Check");
        (void)NSLOCTEXT("TraceMotive", "Choose a class.", "Choose a class.");
        (void)NSLOCTEXT("TraceMotive", "Choose a target and the action to run when it is reached, then arm it.", "Choose a target and the action to run when it is reached, then arm it.");
        (void)NSLOCTEXT("TraceMotive", "Choose at least one variable.", "Choose at least one variable.");
        (void)NSLOCTEXT("TraceMotive", "Choose two different actors.", "Choose two different actors.");
        (void)NSLOCTEXT("TraceMotive", "Class", "Class");
        (void)NSLOCTEXT("TraceMotive", "Classes", "Classes");
        (void)NSLOCTEXT("TraceMotive", "Clear", "Clear");
        (void)NSLOCTEXT("TraceMotive", "Clear all notes for this function, including saved notes.", "Clear all notes for this function, including saved notes.");
        (void)NSLOCTEXT("TraceMotive", "Clear history", "Clear history");
        (void)NSLOCTEXT("TraceMotive", "Clear pair", "Clear pair");
        (void)NSLOCTEXT("TraceMotive", "Click a PIE UMG widget once and inspect the short Blueprint function flow it triggers.", "Click a PIE UMG widget once and inspect the short Blueprint function flow it triggers.");
        (void)NSLOCTEXT("TraceMotive", "Click an editor area to capture shortcuts. Current default: {0}", "Click an editor area to capture shortcuts. Current default: {0}");
        (void)NSLOCTEXT("TraceMotive", "Click anywhere in PIE to capture", "Click anywhere in PIE to capture");
        (void)NSLOCTEXT("TraceMotive", "Click anywhere in PIE to capture the Slate, UMG, actor hit, and bound-event path.", "Click anywhere in PIE to capture the Slate, UMG, actor hit, and bound-event path.");
        (void)NSLOCTEXT("TraceMotive", "Click history", "Click history");
        (void)NSLOCTEXT("TraceMotive", "Click once in an editor area to lock this panel to that context. Limit: project-specific or plugin-specific shortcuts may differ from this guide.", "Click once in an editor area to lock this panel to that context. Limit: project-specific or plugin-specific shortcuts may differ from this guide.");
        (void)NSLOCTEXT("TraceMotive", "Click/Touch Event Diagnostics", "Click/Touch Event Diagnostics");
        (void)NSLOCTEXT("TraceMotive", "Collapse All", "Collapse All");
        (void)NSLOCTEXT("TraceMotive", "Collision", "Collision");
        (void)NSLOCTEXT("TraceMotive", "Collision Pair Analyzer", "Collision Pair Analyzer");
        (void)NSLOCTEXT("TraceMotive", "Collision geometry may be missing", "Collision geometry may be missing");
        (void)NSLOCTEXT("TraceMotive", "Collision is disabled", "Collision is disabled");
        (void)NSLOCTEXT("TraceMotive", "Collision modes do not share a common path", "Collision modes do not share a common path");
        (void)NSLOCTEXT("TraceMotive", "Collision shapes currently overlap", "Collision shapes currently overlap");
        (void)NSLOCTEXT("TraceMotive", "Compare two actors at runtime and explain why their primitive components do not Block.", "Compare two actors at runtime and explain why their primitive components do not Block.");
        (void)NSLOCTEXT("TraceMotive", "Completed PIE Log Analysis", "Completed PIE Log Analysis");
        (void)NSLOCTEXT("TraceMotive", "Completed PIE Logs", "Completed PIE Logs");
        (void)NSLOCTEXT("TraceMotive", "Completed PIE log analysis reads Saved/Logs. Instance and function recovery is evidence-based inference.", "Completed PIE log analysis reads Saved/Logs. Instance and function recovery is evidence-based inference.");
        (void)NSLOCTEXT("TraceMotive", "Component", "Component");
        (void)NSLOCTEXT("TraceMotive", "Component Details", "Component Details");
        (void)NSLOCTEXT("TraceMotive", "Component is not registered", "Component is not registered");
        (void)NSLOCTEXT("TraceMotive", "Component name, class, or path matched.", "Component name, class, or path matched.");
        (void)NSLOCTEXT("TraceMotive", "Component tag matched.", "Component tag matched.");
        (void)NSLOCTEXT("TraceMotive", "Components", "Components");
        (void)NSLOCTEXT("TraceMotive", "Components are not currently touching", "Components are not currently touching");
        (void)NSLOCTEXT("TraceMotive", "Confidence: Medium. This is a target-scoped pointer diagnosis; unloaded Blueprints, native code, dynamic delegates, and post-event input-mode changes may need Details/PIE confirmation.", "Confidence: Medium. This is a target-scoped pointer diagnosis; unloaded Blueprints, native code, dynamic delegates, and post-event input-mode changes may need Details/PIE confirmation.");
        (void)NSLOCTEXT("TraceMotive", "Configuration", "Configuration");
        (void)NSLOCTEXT("TraceMotive", "Confirmed - Normal", "Confirmed - Normal");
        (void)NSLOCTEXT("TraceMotive", "Consumed by UI", "Consumed by UI");
        (void)NSLOCTEXT("TraceMotive", "Contact / sweep evidence", "Contact / sweep evidence");
        (void)NSLOCTEXT("TraceMotive", "Context Shortcuts", "Context Shortcuts");
        (void)NSLOCTEXT("TraceMotive", "Control gameplay time dilation and audio playback speed together.", "Control gameplay time dilation and audio playback speed together.");
        (void)NSLOCTEXT("TraceMotive", "Copy", "Copy");
        (void)NSLOCTEXT("TraceMotive", "Copy All", "Copy All");
        (void)NSLOCTEXT("TraceMotive", "Copy Classes", "Copy Classes");
        (void)NSLOCTEXT("TraceMotive", "Copy Logs", "Copy Logs");
        (void)NSLOCTEXT("TraceMotive", "Copy Report", "Copy Report");
        (void)NSLOCTEXT("TraceMotive", "Copy Results", "Copy Results");
        (void)NSLOCTEXT("TraceMotive", "Copy Status", "Copy Status");
        (void)NSLOCTEXT("TraceMotive", "Copy all", "Copy all");
        (void)NSLOCTEXT("TraceMotive", "Copy all paths and match reasons to the clipboard", "Copy all paths and match reasons to the clipboard");
        (void)NSLOCTEXT("TraceMotive", "Copy all recent packaging log lines.", "Copy all recent packaging log lines.");
        (void)NSLOCTEXT("TraceMotive", "Copy errors", "Copy errors");
        (void)NSLOCTEXT("TraceMotive", "Copy log", "Copy log");
        (void)NSLOCTEXT("TraceMotive", "Copy only error-like packaging log lines.", "Copy only error-like packaging log lines.");
        (void)NSLOCTEXT("TraceMotive", "Copy report", "Copy report");
        (void)NSLOCTEXT("TraceMotive", "Copy the deduplicated class summary.", "Copy the deduplicated class summary.");
        (void)NSLOCTEXT("TraceMotive", "Copy this class summary.", "Copy this class summary.");
        (void)NSLOCTEXT("TraceMotive", "Copy this confidence step", "Copy this confidence step");
        (void)NSLOCTEXT("TraceMotive", "Copy this error's debug info.", "Copy this error's debug info.");
        (void)NSLOCTEXT("TraceMotive", "Current", "Current");
        (void)NSLOCTEXT("TraceMotive", "Current stage progress", "Current stage progress");
        (void)NSLOCTEXT("TraceMotive", "Current work", "Current work");
        (void)NSLOCTEXT("TraceMotive", "Currently shows every source.", "Currently shows every source.");
        (void)NSLOCTEXT("TraceMotive", "Debug Session", "Debug Session");
        (void)NSLOCTEXT("TraceMotive", "Dedup Instances", "Dedup Instances");
        (void)NSLOCTEXT("TraceMotive", "Detail Trace", "Detail Trace");
        (void)NSLOCTEXT("TraceMotive", "Details", "Details");
        (void)NSLOCTEXT("TraceMotive", "Details variable name/display/category matched.", "Details variable name/display/category matched.");
        (void)NSLOCTEXT("TraceMotive", "Details variable value matched.", "Details variable value matched.");
        (void)NSLOCTEXT("TraceMotive", "Detect audio playback during PIE and show which actor, component, Blueprint function, or runtime source triggered it.", "Detect audio playback during PIE and show which actor, component, Blueprint function, or runtime source triggered it.");
        (void)NSLOCTEXT("TraceMotive", "Detects AudioComponent playback during Editor/PIE and records the best matched Blueprint or actor source.", "Detects AudioComponent playback during Editor/PIE and records the best matched Blueprint or actor source.");
        (void)NSLOCTEXT("TraceMotive", "Diagnose the seven stages of click/touch delivery.", "Diagnose the seven stages of click/touch delivery.");
        (void)NSLOCTEXT("TraceMotive", "Diagnosis: Block-capable pair exists; movement path unverified", "Diagnosis: Block-capable pair exists; movement path unverified");
        (void)NSLOCTEXT("TraceMotive", "Diagnosis: actor/world state prevents collision", "Diagnosis: actor/world state prevents collision");
        (void)NSLOCTEXT("TraceMotive", "Diagnosis: no Block-capable pair found", "Diagnosis: no Block-capable pair found");
        (void)NSLOCTEXT("TraceMotive", "Diagnosis: swept query blocking was observed", "Diagnosis: swept query blocking was observed");
        (void)NSLOCTEXT("TraceMotive", "Double-click to open. Place adds at origin, Here adds at the current view, or drag into the level.", "Double-click to open. Place adds at origin, Here adds at the current view, or drag into the level.");
        (void)NSLOCTEXT("TraceMotive", "Drop an actor here, or replace it with the current selection.", "Drop an actor here, or replace it with the current selection.");
        (void)NSLOCTEXT("TraceMotive", "EV", "EV");
        (void)NSLOCTEXT("TraceMotive", "Elapsed", "Elapsed");
        (void)NSLOCTEXT("TraceMotive", "Enable editing to remove favorites or reorder the list.", "Enable editing to remove favorites or reorder the list.");
        (void)NSLOCTEXT("TraceMotive", "Enhanced Outliner Search", "Enhanced Outliner Search");
        (void)NSLOCTEXT("TraceMotive", "Enter a query to search currently loaded level instances.", "Enter a query to search currently loaded level instances.");
        (void)NSLOCTEXT("TraceMotive", "Enter both variable name and value to run a pair search.", "Enter both variable name and value to run a pair search.");
        (void)NSLOCTEXT("TraceMotive", "Erase notes by dragging over drawn strokes.", "Erase notes by dragging over drawn strokes.");
        (void)NSLOCTEXT("TraceMotive", "Eraser", "Eraser");
        (void)NSLOCTEXT("TraceMotive", "Error", "Error");
        (void)NSLOCTEXT("TraceMotive", "Estimated progress - the upper bar is the current stage, the lower bar is total packaging progress.", "Estimated progress - the upper bar is the current stage, the lower bar is total packaging progress.");
        (void)NSLOCTEXT("TraceMotive", "Estimated remaining", "Estimated remaining");
        (void)NSLOCTEXT("TraceMotive", "Event log", "Event log");
        (void)NSLOCTEXT("TraceMotive", "Events", "Events");
        (void)NSLOCTEXT("TraceMotive", "Expand All", "Expand All");
        (void)NSLOCTEXT("TraceMotive", "Explain why two selected actors do not block each other.", "Explain why two selected actors do not block each other.");
        (void)NSLOCTEXT("TraceMotive", "Failed", "Failed");
        (void)NSLOCTEXT("TraceMotive", "Failure analysis", "Failure analysis");
        (void)NSLOCTEXT("TraceMotive", "Filter", "Filter");
        (void)NSLOCTEXT("TraceMotive", "Filter by Blueprint, graph, node, property, reason", "Filter by Blueprint, graph, node, property, reason");
        (void)NSLOCTEXT("TraceMotive", "Filter favorite assets and levels", "Filter favorite assets and levels");
        (void)NSLOCTEXT("TraceMotive", "Find Exact Blueprint Usage", "Find Exact Blueprint Usage");
        (void)NSLOCTEXT("TraceMotive", "Find exact Blueprint graph node, pin, or default property usage for this asset.", "Find exact Blueprint graph node, pin, or default property usage for this asset.");
        (void)NSLOCTEXT("TraceMotive", "Find where click/touch delivery stops without changing game input behavior.", "Find where click/touch delivery stops without changing game input behavior.");
        (void)NSLOCTEXT("TraceMotive", "Focus", "Focus");
        (void)NSLOCTEXT("TraceMotive", "Function", "Function");
        (void)NSLOCTEXT("TraceMotive", "Generate Overlap Events does not control blocking", "Generate Overlap Events does not control blocking");
        (void)NSLOCTEXT("TraceMotive", "Global Speed Control", "Global Speed Control");
        (void)NSLOCTEXT("TraceMotive", "Here", "Here");
        (void)NSLOCTEXT("TraceMotive", "Hide Trace", "Hide Trace");
        (void)NSLOCTEXT("TraceMotive", "Hide full diagnostic steps ^", "Hide full diagnostic steps ^");
        (void)NSLOCTEXT("TraceMotive", "Hierarchy", "Hierarchy");
        (void)NSLOCTEXT("TraceMotive", "High confidence for swept query blocking; gameplay path still must use Sweep/FHitResult", "High confidence for swept query blocking; gameplay path still must use Sweep/FHitResult");
        (void)NSLOCTEXT("TraceMotive", "High confidence: Block is not possible with current inspected settings", "High confidence: Block is not possible with current inspected settings");
        (void)NSLOCTEXT("TraceMotive", "High speed (over 6x): physics, timers, complex animation, and networking can become unreliable. Prefer Skip to Target.", "High speed (over 6x): physics, timers, complex animation, and networking can become unreliable. Prefer Skip to Target.");
        (void)NSLOCTEXT("TraceMotive", "Hit-event settings are separate", "Hit-event settings are separate");
        (void)NSLOCTEXT("TraceMotive", "INFO", "INFO");
        (void)NSLOCTEXT("TraceMotive", "Idle", "Idle");
        (void)NSLOCTEXT("TraceMotive", "Ignore State", "Ignore State");
        (void)NSLOCTEXT("TraceMotive", "Ignored", "Ignored");
        (void)NSLOCTEXT("TraceMotive", "Info", "Info");
        (void)NSLOCTEXT("TraceMotive", "Input mappings have not been scanned. Select a target or press Rescan Input Mappings.", "Input mappings have not been scanned. Select a target or press Rescan Input Mappings.");
        (void)NSLOCTEXT("TraceMotive", "Inspected pairs", "Inspected pairs");
        (void)NSLOCTEXT("TraceMotive", "Instance dedup on", "Instance dedup on");
        (void)NSLOCTEXT("TraceMotive", "Instances", "Instances");
        (void)NSLOCTEXT("TraceMotive", "Invalid component", "Invalid component");
        (void)NSLOCTEXT("TraceMotive", "Investigate live Blueprint errors and completed PIE logs in one workspace.", "Investigate live Blueprint errors and completed PIE logs in one workspace.");
        (void)NSLOCTEXT("TraceMotive", "Last click - waiting for PIE capture", "Last click - waiting for PIE capture");
        (void)NSLOCTEXT("TraceMotive", "Latest:", "Latest:");
        (void)NSLOCTEXT("TraceMotive", "Lifecycle", "Lifecycle");
        (void)NSLOCTEXT("TraceMotive", "Likely causes are extracted from the final UAT/cook/build log lines. Use Open target when an asset, Blueprint, class, or source file can be inferred.", "Likely causes are extracted from the final UAT/cook/build log lines. Use Open target when an asset, Blueprint, class, or source file can be inferred.");
        (void)NSLOCTEXT("TraceMotive", "Limitations: pitch-based audio speed can affect sound pitch, and some systems with custom clocks, media playback, network replication, or native timers may not follow global time dilation exactly.", "Limitations: pitch-based audio speed can affect sound pitch, and some systems with custom clocks, media playback, network replication, or native timers may not follow global time dilation exactly.");
        (void)NSLOCTEXT("TraceMotive", "Listening while this window is open.", "Listening while this window is open.");
        (void)NSLOCTEXT("TraceMotive", "Live", "Live");
        (void)NSLOCTEXT("TraceMotive", "Live Trace", "Live Trace");
        (void)NSLOCTEXT("TraceMotive", "Live UUserWidget", "Live UUserWidget");
        (void)NSLOCTEXT("TraceMotive", "Matches Output Log text or category, case-insensitively.", "Matches Output Log text or category, case-insensitively.");
        (void)NSLOCTEXT("TraceMotive", "Matches the selected Blueprint class (including children) and exact function name.", "Matches the selected Blueprint class (including children) and exact function name.");
        (void)NSLOCTEXT("TraceMotive", "Material", "Material");
        (void)NSLOCTEXT("TraceMotive", "Maximum 20x: frame skips, timer order changes, collision misses, and UI/audio desync can occur. Use only with Skip to Target.", "Maximum 20x: frame skips, timer order changes, collision misses, and UI/audio desync can occur. Use only with Skip to Target.");
        (void)NSLOCTEXT("TraceMotive", "Medium confidence: current query contact exists, but movement blocking path is unverified", "Medium confidence: current query contact exists, but movement blocking path is unverified");
        (void)NSLOCTEXT("TraceMotive", "Medium confidence: settings allow Block, but actual movement blocking is unverified", "Medium confidence: settings allow Block, but actual movement blocking is unverified");
        (void)NSLOCTEXT("TraceMotive", "Monitor packaging stages and estimated overall progress.", "Monitor packaging stages and estimated overall progress.");
        (void)NSLOCTEXT("TraceMotive", "Mouse-under-widget path: {0}", "Mouse-under-widget path: {0}");
        (void)NSLOCTEXT("TraceMotive", "Move the active viewport camera to the runtime owner actor.", "Move the active viewport camera to the runtime owner actor.");
        (void)NSLOCTEXT("TraceMotive", "MoveComponent ignore list excludes this pair", "MoveComponent ignore list excludes this pair");
        (void)NSLOCTEXT("TraceMotive", "MoveComponent-style node found. Confirm that this path uses swept movement and does not ignore the blocking component.", "MoveComponent-style node found. Confirm that this path uses swept movement and does not ignore the blocking component.");
        (void)NSLOCTEXT("TraceMotive", "Movement API cannot be inferred from static state", "Movement API cannot be inferred from static state");
        (void)NSLOCTEXT("TraceMotive", "Name", "Name");
        (void)NSLOCTEXT("TraceMotive", "No Blueprint call paths found.", "No Blueprint call paths found.");
        (void)NSLOCTEXT("TraceMotive", "No Blueprint runtime errors captured yet. Start PIE with this window open.", "No Blueprint runtime errors captured yet. Start PIE with this window open.");
        (void)NSLOCTEXT("TraceMotive", "No audio playback captured yet. Keep this window open, then start PIE.", "No audio playback captured yet. Keep this window open, then start PIE.");
        (void)NSLOCTEXT("TraceMotive", "No changes match the current filters.", "No changes match the current filters.");
        (void)NSLOCTEXT("TraceMotive", "No click history yet.", "No click history yet.");
        (void)NSLOCTEXT("TraceMotive", "No component changes captured yet.", "No component changes captured yet.");
        (void)NSLOCTEXT("TraceMotive", "No component pair resolves to Block. Review the component pair responses below.", "No component pair resolves to Block. Review the component pair responses below.");
        (void)NSLOCTEXT("TraceMotive", "No current overlap contact", "No current overlap contact");
        (void)NSLOCTEXT("TraceMotive", "No direct collision-option fix was detected. Prefer testing the actual movement path with Sweep=true and inspect the returned FHitResult.", "No direct collision-option fix was detected. Prefer testing the actual movement path with Sweep=true and inspect the returned FHitResult.");
        (void)NSLOCTEXT("TraceMotive", "No flow captured yet.", "No flow captured yet.");
        (void)NSLOCTEXT("TraceMotive", "No live UUserWidget captured yet. Keep this tab open, then start PIE or open a UI.", "No live UUserWidget captured yet. Keep this tab open, then start PIE or open a UI.");
        (void)NSLOCTEXT("TraceMotive", "No live actor references found.", "No live actor references found.");
        (void)NSLOCTEXT("TraceMotive", "No logs yet.", "No logs yet.");
        (void)NSLOCTEXT("TraceMotive", "No matches found in the current editor world.", "No matches found in the current editor world.");
        (void)NSLOCTEXT("TraceMotive", "No matching variables", "No matching variables");
        (void)NSLOCTEXT("TraceMotive", "No obvious Sweep=false or Teleport movement node was found in the selected actors' Blueprint class chain.", "No obvious Sweep=false or Teleport movement node was found in the selected actors' Blueprint class chain.");
        (void)NSLOCTEXT("TraceMotive", "No primitive collision component", "No primitive collision component");
        (void)NSLOCTEXT("TraceMotive", "No specific error line was detected. Check the recent packaging log below.", "No specific error line was detected. Check the recent packaging log below.");
        (void)NSLOCTEXT("TraceMotive", "No target selected. Use a selected asset/actor or pick the next PIE click/touch.", "No target selected. Use a selected asset/actor or pick the next PIE click/touch.");
        (void)NSLOCTEXT("TraceMotive", "No traceable properties", "No traceable properties");
        (void)NSLOCTEXT("TraceMotive", "No widget lifecycle event captured yet.", "No widget lifecycle event captured yet.");
        (void)NSLOCTEXT("TraceMotive", "Node", "Node");
        (void)NSLOCTEXT("TraceMotive", "Not reached", "Not reached");
        (void)NSLOCTEXT("TraceMotive", "Notes", "Notes");
        (void)NSLOCTEXT("TraceMotive", "Notes saved for this function.", "Notes saved for this function.");
        (void)NSLOCTEXT("TraceMotive", "Observe class properties during PIE as synchronized timeline lanes.", "Observe class properties during PIE as synchronized timeline lanes.");
        (void)NSLOCTEXT("TraceMotive", "Open", "Open");
        (void)NSLOCTEXT("TraceMotive", "Open Asset & Level Favorites", "Open Asset & Level Favorites");
        (void)NSLOCTEXT("TraceMotive", "Open BP", "Open BP");
        (void)NSLOCTEXT("TraceMotive", "Open Location", "Open Location");
        (void)NSLOCTEXT("TraceMotive", "Open Node", "Open Node");
        (void)NSLOCTEXT("TraceMotive", "Open a window that speeds up gameplay time dilation and audio playback together.", "Open a window that speeds up gameplay time dilation and audio playback together.");
        (void)NSLOCTEXT("TraceMotive", "Open placeable asset and level favorites.", "Open placeable asset and level favorites.");
        (void)NSLOCTEXT("TraceMotive", "Open target", "Open target");
        (void)NSLOCTEXT("TraceMotive", "Open the asset and level favorites window.", "Open the asset and level favorites window.");
        (void)NSLOCTEXT("TraceMotive", "Open the click/touch delivery diagnostics panel.", "Open the click/touch delivery diagnostics panel.");
        (void)NSLOCTEXT("TraceMotive", "Open the matching Blueprint node when available.", "Open the matching Blueprint node when available.");
        (void)NSLOCTEXT("TraceMotive", "Open the most recent Blueprint node for this class, or the Blueprint asset.", "Open the most recent Blueprint node for this class, or the Blueprint asset.");
        (void)NSLOCTEXT("TraceMotive", "Open the packaging progress monitor.", "Open the packaging progress monitor.");
        (void)NSLOCTEXT("TraceMotive", "Open the placeable asset and level favorites window.", "Open the placeable asset and level favorites window.");
        (void)NSLOCTEXT("TraceMotive", "Open the related asset, Blueprint, or source file when it can be inferred.", "Open the related asset, Blueprint, or source file when it can be inferred.");
        (void)NSLOCTEXT("TraceMotive", "Open the two-actor runtime collision diagnosis window.", "Open the two-actor runtime collision diagnosis window.");
        (void)NSLOCTEXT("TraceMotive", "Open this window before PIE to capture audio playback sources.", "Open this window before PIE to capture audio playback sources.");
        (void)NSLOCTEXT("TraceMotive", "Other", "Other");
        (void)NSLOCTEXT("TraceMotive", "Output Log text", "Output Log text");
        (void)NSLOCTEXT("TraceMotive", "Overall progress", "Overall progress");
        (void)NSLOCTEXT("TraceMotive", "Overlap events are also disabled", "Overlap events are also disabled");
        (void)NSLOCTEXT("TraceMotive", "PASS", "PASS");
        (void)NSLOCTEXT("TraceMotive", "PIE ended. Audio trace remains armed for the next play session.", "PIE ended. Audio trace remains armed for the next play session.");
        (void)NSLOCTEXT("TraceMotive", "PIE ended. Trace is armed for the next session.", "PIE ended. Trace is armed for the next session.");
        (void)NSLOCTEXT("TraceMotive", "PIE started. Existing AudioComponents scanned.", "PIE started. Existing AudioComponents scanned.");
        (void)NSLOCTEXT("TraceMotive", "PIE started. Trace is active.", "PIE started. Trace is active.");
        (void)NSLOCTEXT("TraceMotive", "PIE starting. Audio trace is armed.", "PIE starting. Audio trace is armed.");
        (void)NSLOCTEXT("TraceMotive", "Package Progress", "Package Progress");
        (void)NSLOCTEXT("TraceMotive", "Packaging error log", "Packaging error log");
        (void)NSLOCTEXT("TraceMotive", "Packaging failed", "Packaging failed");
        (void)NSLOCTEXT("TraceMotive", "Pass", "Pass");
        (void)NSLOCTEXT("TraceMotive", "Passed", "Passed");
        (void)NSLOCTEXT("TraceMotive", "Pause", "Pause");
        (void)NSLOCTEXT("TraceMotive", "Pause PIE/Game (restore 1x)", "Pause PIE/Game (restore 1x)");
        (void)NSLOCTEXT("TraceMotive", "Paused", "Paused");
        (void)NSLOCTEXT("TraceMotive", "Persist a diagnosis, route between tools, and compare Before/After actor state.", "Persist a diagnosis, route between tools, and compare Before/After actor state.");
        (void)NSLOCTEXT("TraceMotive", "PhysicsOnly contacts, Chaos simulation details, complex BodySetup cases, and custom primitive implementations cannot be fully proven by this panel.", "PhysicsOnly contacts, Chaos simulation details, complex BodySetup cases, and custom primitive implementations cannot be fully proven by this panel.");
        (void)NSLOCTEXT("TraceMotive", "Pick Next PIE Click/Touch", "Pick Next PIE Click/Touch");
        (void)NSLOCTEXT("TraceMotive", "Pick Next PIE Click/Touch inspects only the UMG widget or Visibility-hit actor under that pointer event. Manual actor/widget selection is also available; no project-wide Blueprint load is performed.", "Pick Next PIE Click/Touch inspects only the UMG widget or Visibility-hit actor under that pointer event. Manual actor/widget selection is also available; no project-wide Blueprint load is performed.");
        (void)NSLOCTEXT("TraceMotive", "Pin", "Pin");
        (void)NSLOCTEXT("TraceMotive", "Pinned", "Pinned");
        (void)NSLOCTEXT("TraceMotive", "Pinned Only", "Pinned Only");
        (void)NSLOCTEXT("TraceMotive", "Place", "Place");
        (void)NSLOCTEXT("TraceMotive", "Place this asset at the current level viewport camera location.", "Place this asset at the current level viewport camera location.");
        (void)NSLOCTEXT("TraceMotive", "Place this asset at world origin (0,0,0).", "Place this asset at world origin (0,0,0).");
        (void)NSLOCTEXT("TraceMotive", "Platform", "Platform");
        (void)NSLOCTEXT("TraceMotive", "Press an event Details button to show additional log information here.", "Press an event Details button to show additional log information here.");
        (void)NSLOCTEXT("TraceMotive", "Quick fix tips", "Quick fix tips");
        (void)NSLOCTEXT("TraceMotive", "Raw Log", "Raw Log");
        (void)NSLOCTEXT("TraceMotive", "Reached target", "Reached target");
        (void)NSLOCTEXT("TraceMotive", "Reads project Saved/Logs after PIE and extracts instance/function candidates from Blueprint Runtime Error log blocks. Confidence is heuristic.", "Reads project Saved/Logs after PIE and extracts instance/function candidates from Blueprint Runtime Error log blocks. Confidence is heuristic.");
        (void)NSLOCTEXT("TraceMotive", "Recent changes", "Recent changes");
        (void)NSLOCTEXT("TraceMotive", "Recent packaging log", "Recent packaging log");
        (void)NSLOCTEXT("TraceMotive", "Reference", "Reference");
        (void)NSLOCTEXT("TraceMotive", "Referencers", "Referencers");
        (void)NSLOCTEXT("TraceMotive", "Refresh", "Refresh");
        (void)NSLOCTEXT("TraceMotive", "Refresh live widgets", "Refresh live widgets");
        (void)NSLOCTEXT("TraceMotive", "Remove this entry from the favorites list. This does not delete actors or assets.", "Remove this entry from the favorites list. This does not delete actors or assets.");
        (void)NSLOCTEXT("TraceMotive", "Replace With Selected", "Replace With Selected");
        (void)NSLOCTEXT("TraceMotive", "Rescan", "Rescan");
        (void)NSLOCTEXT("TraceMotive", "Rescan Input Mappings", "Rescan Input Mappings");
        (void)NSLOCTEXT("TraceMotive", "Reset", "Reset");
        (void)NSLOCTEXT("TraceMotive", "Restore 1x", "Restore 1x");
        (void)NSLOCTEXT("TraceMotive", "Result", "Result");
        (void)NSLOCTEXT("TraceMotive", "Resume", "Resume");
        (void)NSLOCTEXT("TraceMotive", "Run required", "Run required");
        (void)NSLOCTEXT("TraceMotive", "Running", "Running");
        (void)NSLOCTEXT("TraceMotive", "Runtime Error Investigation", "Runtime Error Investigation");
        (void)NSLOCTEXT("TraceMotive", "Runtime Instance", "Runtime Instance");
        (void)NSLOCTEXT("TraceMotive", "Runtime physics state is missing", "Runtime physics state is missing");
        (void)NSLOCTEXT("TraceMotive", "S", "S");
        (void)NSLOCTEXT("TraceMotive", "Save", "Save");
        (void)NSLOCTEXT("TraceMotive", "Save Snapshot", "Save Snapshot");
        (void)NSLOCTEXT("TraceMotive", "Save notes for this function and restore them the next time it is opened.", "Save notes for this function and restore them the next time it is opened.");
        (void)NSLOCTEXT("TraceMotive", "Search Boost: OFF", "Search Boost: OFF");
        (void)NSLOCTEXT("TraceMotive", "Search Boost: ON", "Search Boost: ON");
        (void)NSLOCTEXT("TraceMotive", "Search actor tags, variable names, and variable values in current level instances.", "Search actor tags, variable names, and variable values in current level instances.");
        (void)NSLOCTEXT("TraceMotive", "Search actor, component, tag, variable name, or variable value", "Search actor, component, tag, variable name, or variable value");
        (void)NSLOCTEXT("TraceMotive", "Search and select Blueprint class...", "Search and select Blueprint class...");
        (void)NSLOCTEXT("TraceMotive", "Search classes", "Search classes");
        (void)NSLOCTEXT("TraceMotive", "Search details", "Search details");
        (void)NSLOCTEXT("TraceMotive", "Search events", "Search events");
        (void)NSLOCTEXT("TraceMotive", "Search loaded editor-world instances without loading every Blueprint. Includes tags, Details variable names, and variable values.", "Search loaded editor-world instances without loading every Blueprint. Includes tags, Details variable names, and variable values.");
        (void)NSLOCTEXT("TraceMotive", "Search loaded level instances, tags, and Details variables without freezing the editor.", "Search loaded level instances, tags, and Details variables without freezing the editor.");
        (void)NSLOCTEXT("TraceMotive", "Search variables by name, type, category or class", "Search variables by name, type, category or class");
        (void)NSLOCTEXT("TraceMotive", "Search widget or class", "Search widget or class");
        (void)NSLOCTEXT("TraceMotive", "Select", "Select");
        (void)NSLOCTEXT("TraceMotive", "Select a change card to inspect its captured value.", "Select a change card to inspect its captured value.");
        (void)NSLOCTEXT("TraceMotive", "Select a class and variables", "Select a class and variables");
        (void)NSLOCTEXT("TraceMotive", "Select class", "Select class");
        (void)NSLOCTEXT("TraceMotive", "Select function...", "Select function...");
        (void)NSLOCTEXT("TraceMotive", "Select or capture actor A and B, then run Analyze.", "Select or capture actor A and B, then run Analyze.");
        (void)NSLOCTEXT("TraceMotive", "Select properties to trace.", "Select properties to trace.");
        (void)NSLOCTEXT("TraceMotive", "Select the runtime owner actor instance in the editor.", "Select the runtime owner actor instance in the editor.");
        (void)NSLOCTEXT("TraceMotive", "Select variables", "Select variables");
        (void)NSLOCTEXT("TraceMotive", "Selected only", "Selected only");
        (void)NSLOCTEXT("TraceMotive", "Selection required", "Selection required");
        (void)NSLOCTEXT("TraceMotive", "Short sweep probe did not hit this pair", "Short sweep probe did not hit this pair");
        (void)NSLOCTEXT("TraceMotive", "Show Classes", "Show Classes");
        (void)NSLOCTEXT("TraceMotive", "Show Errors", "Show Errors");
        (void)NSLOCTEXT("TraceMotive", "Show Ignored", "Show Ignored");
        (void)NSLOCTEXT("TraceMotive", "Show errors captured while PIE is running.", "Show errors captured while PIE is running.");
        (void)NSLOCTEXT("TraceMotive", "Show only one latest row per runtime instance. Counts still include repeated events and merged error groups.", "Show only one latest row per runtime instance. Counts still include repeated events and merged error groups.");
        (void)NSLOCTEXT("TraceMotive", "Show shortcuts for the editor panel currently under the mouse, such as Material Graph, Blueprint Graph, viewport, or Content Browser.", "Show shortcuts for the editor panel currently under the mouse, such as Material Graph, Blueprint Graph, viewport, or Content Browser.");
        (void)NSLOCTEXT("TraceMotive", "Show target and match details", "Show target and match details");
        (void)NSLOCTEXT("TraceMotive", "Show useful shortcuts for the editor area currently under the mouse.", "Show useful shortcuts for the editor area currently under the mouse.");
        (void)NSLOCTEXT("TraceMotive", "Showing", "Showing");
        (void)NSLOCTEXT("TraceMotive", "Shows opened UMG widget files, creation location, and child widget on/off control source.", "Shows opened UMG widget files, creation location, and child widget on/off control source.");
        (void)NSLOCTEXT("TraceMotive", "Skip", "Skip");
        (void)NSLOCTEXT("TraceMotive", "Skip-only speed (8x+): not recommended for normal play. Use this to reach a log or event target, then pause.", "Skip-only speed (8x+): not recommended for normal play. Use this to reach a log or event target, then pause.");
        (void)NSLOCTEXT("TraceMotive", "Source compile error", "Source compile error");
        (void)NSLOCTEXT("TraceMotive", "Speed", "Speed");
        (void)NSLOCTEXT("TraceMotive", "Speed snaps to 0.1x steps from 0.1x to 20x. Integer values are rounded cleanly; 1x restores normal time and audio pitch.", "Speed snaps to 0.1x steps from 0.1x to 20x. Integer values are rounded cleanly; 1x restores normal time and audio pitch.");
        (void)NSLOCTEXT("TraceMotive", "Start trace", "Start trace");
        (void)NSLOCTEXT("TraceMotive", "Stats", "Stats");
        (void)NSLOCTEXT("TraceMotive", "Status", "Status");
        (void)NSLOCTEXT("TraceMotive", "Succeeded", "Succeeded");
        (void)NSLOCTEXT("TraceMotive", "Summary", "Summary");
        (void)NSLOCTEXT("TraceMotive", "Suspicious movement nodes", "Suspicious movement nodes");
        (void)NSLOCTEXT("TraceMotive", "Swap A / B", "Swap A / B");
        (void)NSLOCTEXT("TraceMotive", "Sweep probe skipped: component has no world.", "Sweep probe skipped: component has no world.");
        (void)NSLOCTEXT("TraceMotive", "Sweep probe skipped: components are invalid or not in the same world.", "Sweep probe skipped: components are invalid or not in the same world.");
        (void)NSLOCTEXT("TraceMotive", "Sweep probe skipped: the components share the same center, so no reliable sweep direction could be inferred.", "Sweep probe skipped: the components share the same center, so no reliable sweep direction could be inferred.");
        (void)NSLOCTEXT("TraceMotive", "Sweep=false, Teleport, custom ignore lists, or a MovementComponent using a non-blocking UpdatedComponent can bypass otherwise valid blocking collision.", "Sweep=false, Teleport, custom ignore lists, or a MovementComponent using a non-blocking UpdatedComponent can bypass otherwise valid blocking collision.");
        (void)NSLOCTEXT("TraceMotive", "Swept movement can block", "Swept movement can block");
        (void)NSLOCTEXT("TraceMotive", "Sync the Content Browser to this asset, matching the editor Ctrl+B behavior.", "Sync the Content Browser to this asset, matching the editor Ctrl+B behavior.");
        (void)NSLOCTEXT("TraceMotive", "Tag", "Tag");
        (void)NSLOCTEXT("TraceMotive", "Tags", "Tags");
        (void)NSLOCTEXT("TraceMotive", "Target: -", "Target: -");
        (void)NSLOCTEXT("TraceMotive", "Target: {0}", "Target: {0}");
        (void)NSLOCTEXT("TraceMotive", "Teleport-style movement can bypass normal swept blocking. Verify this is intentional for collision-critical movement.", "Teleport-style movement can bypass normal swept blocking. Verify this is intentional for collision-critical movement.");
        (void)NSLOCTEXT("TraceMotive", "The pair resolves to Overlap, not Block", "The pair resolves to Overlap, not Block");
        (void)NSLOCTEXT("TraceMotive", "This component pair is configured to Block", "This component pair is configured to Block");
        (void)NSLOCTEXT("TraceMotive", "This panel reports evidence and likely causes, not an absolute collision verdict.", "This panel reports evidence and likely causes, not an absolute collision verdict.");
        (void)NSLOCTEXT("TraceMotive", "This selected item has no captured changes.", "This selected item has no captured changes.");
        (void)NSLOCTEXT("TraceMotive", "Toggle between detailed error groups and deduplicated error classes.", "Toggle between detailed error groups and deduplicated error classes.");
        (void)NSLOCTEXT("TraceMotive", "Toggle freehand notes. Use Save to keep them for this function.", "Toggle freehand notes. Use Save to keep them for this function.");
        (void)NSLOCTEXT("TraceMotive", "Trace", "Trace");
        (void)NSLOCTEXT("TraceMotive", "Trace Details", "Trace Details");
        (void)NSLOCTEXT("TraceMotive", "Trace PIE property changes in synchronized timeline lanes.", "Trace PIE property changes in synchronized timeline lanes.");
        (void)NSLOCTEXT("TraceMotive", "Trace opened UMG widgets and child widget visibility changes during PIE.", "Trace opened UMG widgets and child widget visibility changes during PIE.");
        (void)NSLOCTEXT("TraceMotive", "Trace setup", "Trace setup");
        (void)NSLOCTEXT("TraceMotive", "Tracing {0} - {1} variable(s).", "Tracing {0} - {1} variable(s).");
        (void)NSLOCTEXT("TraceMotive", "Track Blueprint runtime errors with live PIE instance information.", "Track Blueprint runtime errors with live PIE instance information.");
        (void)NSLOCTEXT("TraceMotive", "Transform", "Transform");
        (void)NSLOCTEXT("TraceMotive", "Two actors are required", "Two actors are required");
        (void)NSLOCTEXT("TraceMotive", "Type a search term. The scan runs in small batches so the editor does not freeze.", "Type a search term. The scan runs in small batches so the editor does not freeze.");
        (void)NSLOCTEXT("TraceMotive", "UI", "UI");
        (void)NSLOCTEXT("TraceMotive", "Unique groups", "Unique groups");
        (void)NSLOCTEXT("TraceMotive", "Unpin", "Unpin");
        (void)NSLOCTEXT("TraceMotive", "Use Filter to select a class and variables.", "Use Filter to select a class and variables.");
        (void)NSLOCTEXT("TraceMotive", "Use Selected Actor", "Use Selected Actor");
        (void)NSLOCTEXT("TraceMotive", "Use Selected Widget", "Use Selected Widget");
        (void)NSLOCTEXT("TraceMotive", "Use Two Selected", "Use Two Selected");
        (void)NSLOCTEXT("TraceMotive", "Use more editor time per tick for the next call-chain/search operation.", "Use more editor time per tick for the next call-chain/search operation.");
        (void)NSLOCTEXT("TraceMotive", "Use more editor time per tick to finish searches faster.", "Use more editor time per tick to finish searches faster.");
        (void)NSLOCTEXT("TraceMotive", "Value", "Value");
        (void)NSLOCTEXT("TraceMotive", "Variable Value Trace", "Variable Value Trace");
        (void)NSLOCTEXT("TraceMotive", "Variable name", "Variable name");
        (void)NSLOCTEXT("TraceMotive", "Variable name (ex: a)", "Variable name (ex: a)");
        (void)NSLOCTEXT("TraceMotive", "Variable names", "Variable names");
        (void)NSLOCTEXT("TraceMotive", "Variable pair", "Variable pair");
        (void)NSLOCTEXT("TraceMotive", "Variable value", "Variable value");
        (void)NSLOCTEXT("TraceMotive", "Variable value (ex: abc)", "Variable value (ex: abc)");
        (void)NSLOCTEXT("TraceMotive", "Variable values", "Variable values");
        (void)NSLOCTEXT("TraceMotive", "Verdict", "Verdict");
        (void)NSLOCTEXT("TraceMotive", "View full diagnostic steps for last click v", "View full diagnostic steps for last click v");
        (void)NSLOCTEXT("TraceMotive", "Visibility", "Visibility");
        (void)NSLOCTEXT("TraceMotive", "Waiting", "Waiting");
        (void)NSLOCTEXT("TraceMotive", "Warning: high speed can increase CPU load and make heavy projects, many Tick events, timers, physics, animation, and audio updates unstable or harder to debug.", "Warning: high speed can increase CPU load and make heavy projects, many Tick events, timers, physics, animation, and audio updates unstable or harder to debug.");
        (void)NSLOCTEXT("TraceMotive", "Watch:", "Watch:");
        (void)NSLOCTEXT("TraceMotive", "Widget Click Flow Trace", "Widget Click Flow Trace");
        (void)NSLOCTEXT("TraceMotive", "Widget Lifecycle Trace", "Widget Lifecycle Trace");
        (void)NSLOCTEXT("TraceMotive", "Widget lifecycle trace", "Widget lifecycle trace");
        (void)NSLOCTEXT("TraceMotive", "\\u00D7", "\\u00D7");
        (void)NSLOCTEXT("TraceMotive", "\\u2192", "\\u2192");
        (void)NSLOCTEXT("TraceMotive", "\\u25B6", "\\u25B6");
        (void)NSLOCTEXT("TraceMotive", "\\u25CB", "\\u25CB");
        (void)NSLOCTEXT("TraceMotive", "\\u25CF", "\\u25CF");
        (void)NSLOCTEXT("TraceMotive", "\\u2713", "\\u2713");
        (void)NSLOCTEXT("TraceMotive", "captured", "captured");
        (void)NSLOCTEXT("TraceMotive", "e.g. BossPhase2 or a log category", "e.g. BossPhase2 or a log category");
        (void)NSLOCTEXT("TraceMotive", "now", "now");
        (void)NSLOCTEXT("TraceMotive", "{0} changes", "{0} changes");
        (void)NSLOCTEXT("TraceMotive", "{0} likely issue(s) found", "{0} likely issue(s) found");
        (void)NSLOCTEXT("TraceMotive", "{0} | {1} event groups | {2} live instance(s) | visible: last 45 sec", "{0} | {1} event groups | {2} live instance(s) | visible: last 45 sec");
        (void)NSLOCTEXT("TraceMotive", "|", "|");
    }

    struct FTMLocalizationTextKeyAutoRegister
    {
        FTMLocalizationTextKeyAutoRegister() { RegisterTMLocalizationTextKeys(); }
    };

    static FTMLocalizationTextKeyAutoRegister GTMLocalizationTextKeyAutoRegister;
}
