// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "CPBEditorAutomationBFL.generated.h"

class UDataTable;

UCLASS()
class CPPBUILDERCEDITOR_API UCPBEditorAutomationBFL : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	// EUW usage: expose a file path input, pass the selected CSV and target DataTable, then call this node before generation.
	UFUNCTION(BlueprintCallable, Category = "CPB|Automation")
	static bool ImportCSVToDataTable(const FString& CsvFilePath, UDataTable* TargetDataTable);

	// EUW usage: call after ImportCSVToDataTable to spawn/configure CPB actors into the currently open editor level.
	UFUNCTION(BlueprintCallable, Category = "CPB|Automation")
	static bool AutoGenerateLevelFromDataTable(UDataTable* LevelPlacementTable);

	// EUW usage: deletes actors generated by this automation pass before rerunning the placement pipeline.
	UFUNCTION(BlueprintCallable, Category = "CPB|Automation")
	static bool ClearAutoGeneratedLevelActors();

	// EUW usage: export each workbook tab as CSV into one folder, then call this to create CPB DataTable assets.
	// Expected CSV names: Set_Level.csv, DT_ScenarioFlow.csv, DT_ActionEvent.csv, DT_Dictionary.csv.
	UFUNCTION(BlueprintCallable, Category = "CPB|Automation")
	static bool GenerateDataTablesFromMasterCSVFolder(
		const FString& CsvFolderPath,
		const FString& DestinationAssetFolder = TEXT("/cppBuilderC/Generated/DT"),
		const FString& NarrationAssetRootPath = TEXT("/cppBuilderC/Resource/Sound/Narration"));

	// EUW usage: designers only drop the .xlsx into the configured folder; this creates/updates DataTables without touching the level.
	UFUNCTION(BlueprintCallable, Category = "CPB|Automation")
	static bool GenerateDataTablesFromExcelFolder(
		const FString& ExcelFolderPath = TEXT(""),
		const FString& DestinationAssetFolder = TEXT("/cppBuilderC/Generated/DT"),
		const FString& NarrationAssetRootPath = TEXT("/cppBuilderC/Resource/Sound/Narration"));

	// EUW usage: create/update DataTables from a specific .xlsx path without spawning level actors.
	UFUNCTION(BlueprintCallable, Category = "CPB|Automation")
	static bool GenerateDataTablesFromExcelFile(
		const FString& ExcelFilePath,
		const FString& DestinationAssetFolder = TEXT("/cppBuilderC/Generated/DT"),
		const FString& NarrationAssetRootPath = TEXT("/cppBuilderC/Resource/Sound/Narration"));

	// EUW usage: call after GenerateDataTablesFromMasterCSVFolder to create ACPBSequence actors and register them to the manager.
	UFUNCTION(BlueprintCallable, Category = "CPB|Automation")
	static bool AutoGenerateSequencesFromDataTables(UDataTable* ScenarioFlowTable, UDataTable* ActionEventTable);

	// EUW usage: one-click pipeline for the current editor level: create DT assets, spawn Set_Level actors, create sequences, and wire the manager.
	UFUNCTION(BlueprintCallable, Category = "CPB|Automation")
	static bool RunMasterAutomationFromCSVFolder(
		const FString& CsvFolderPath,
		const FString& DestinationAssetFolder = TEXT("/cppBuilderC/Generated/DT"),
		const FString& NarrationAssetRootPath = TEXT("/cppBuilderC/Resource/Sound/Narration"));

	// EUW usage: designers only drop the .xlsx into the configured folder; this finds the newest workbook and runs the full placement pipeline.
	// If ExcelFolderPath is empty, the tool uses <Project>/Saved/CPBMasterExcel.
	UFUNCTION(BlueprintCallable, Category = "CPB|Automation")
	static bool RunMasterAutomationFromExcelFolder(
		const FString& ExcelFolderPath = TEXT(""),
		const FString& DestinationAssetFolder = TEXT("/cppBuilderC/Generated/DT"),
		const FString& NarrationAssetRootPath = TEXT("/cppBuilderC/Resource/Sound/Narration"));

	// EUW usage: call this when the widget already has an exact .xlsx path from a file picker.
	UFUNCTION(BlueprintCallable, Category = "CPB|Automation")
	static bool RunMasterAutomationFromExcelFile(
		const FString& ExcelFilePath,
		const FString& DestinationAssetFolder = TEXT("/cppBuilderC/Generated/DT"),
		const FString& NarrationAssetRootPath = TEXT("/cppBuilderC/Resource/Sound/Narration"));
};
